require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
source 'https://cdn.cocoapods.org'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# prevents location usage from react-native-vision-camera
$VCEnableLocation = false

# From RNP docs here: https://www.npmjs.com/package/react-native-permissions/v/4.0.1
def node_require(script)
  # Resolve script with node to allow for hoisting
  require `node -p "require.resolve('#{script}', {paths: [process.argv[1]]})" #{__dir__}`.strip
end
  
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# uncomment wanted permissions (also from RNP docs linked above)
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications'
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AriesBifold' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Enable modular headers for CatCrypto to expose Argon2, MD6, SHA3 modules
  pod 'CatCrypto', :modular_headers => true

  #permissions_path = '../node_modules/react-native-permissions/ios'
  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  # use reactNativePermissionsIOS.json for permissions instead!!!


  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix CatCrypto module paths for RNArgon2
    installer.pods_project.targets.each do |target|
      if target.name == 'RNArgon2'
        target.build_configurations.each do |config|
          # Add CatCrypto module map paths to Swift import paths
          catcrypto_path = "#{installer.sandbox.root}/CatCrypto/Sources/ModuleMaps"
          current_paths = config.build_settings['SWIFT_INCLUDE_PATHS'] || '$(inherited)'
          config.build_settings['SWIFT_INCLUDE_PATHS'] = "#{current_paths} \"#{catcrypto_path}/Argon2\" \"#{catcrypto_path}/MD6\" \"#{catcrypto_path}/SHA3\""
        end
      end
    end
  end
end