comment:
  layout: "header"
  behavior: "default"
  max_warnings: 0
# coverage:
#   precision: 2
#   round: down
#   range: "70...100"
#   status:
#     project:
#       default:
#         new_uncovered: 80
