// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Enter",
    "Submit": "Submit",
    "NoneYet!": "None yet!",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "Accept": "Accept",
    "Reject": "Reject",
    "NotNow": "Not now",
    "Share": "Share",
    "Decline": "Decline",
    "Back": "Back",
    "Next": "Next",
    "Continue": "Continue",
    "Info": "Information",
    "ThisDecisionCannotBeChanged.": "This decision cannot be changed.",
    "Failure": "Failure",
    "Success": "Success",
    "SomethingWentWrong": "Something went wrong",
    "Done": "Done",
    "Skip": "Skip",
    "View": "View",
    "Home": "Home",
    "ErrorCode": "Error Code",
    "Okay": "Okay",
    "GoBack": "Go Back",
    "GetStarted": "Get Started",
    "Dismiss": "Dismiss",
    "ShowDetails": "Show Details",
    "TryAgain": "Try Again",
    "Biometrics": "Biometrics",
    "On": "On",
    "Off": "Off",
    "Close": "Close",
  },
  "Date": {
    "ShortFormat": "MMM D, YYYY",
    "LongFormat": "D MMMM YYYY, HH:mm:ss",
    "MonthLong": {
      "January": "January",
      "February": "February",
      "March": "March",
      "April": "April",
      "May": "May",
      "June": "June",
      "July": "July",
      "August": "August",
      "September": "September",
      "October": "October",
      "November": "November",
      "December": "December",
    },
    "MonthShort": {
      "January": "Jan",
      "February": "Feb",
      "March": "Mar",
      "April": "Apr",
      "May": "May",
      "June": "Jun",
      "July": "Jul",
      "August": "Aug",
      "September": "Sep",
      "October": "Oct",
      "November": "Nov",
      "December": "Dec",
    }
  },
  "Language": {
    "English": "English",
    "French": "French",
    "Portuguese": "Portuguese",
  },
  "Error": {
    "Unknown": "Unknown Error",
    "Problem": "A problem has occurred",
    "ErrorCode": "Error code",
    "Title1024": "Unable to accept credential offer.",
    "Message1024": "There was a problem while accepting the credential offer.",
    "Title1025": "Unable to reject credential offer",
    "Message1025": "There was a problem while rejecting the credential offer",
    "Title1026": "Unable to update retrieved credentials.",
    "Message1026": "There was a problem while updating retrieved credentials.",
    "Title1027": "Unable to accept proof request.",
    "Message1027": "There was a problem while accepting the proof request.",
    "Title1028": "Unable to reject proof request",
    "Message1028": "There was a problem while rejecting the proof request",
    "Title1029": "Details	Unable to update retrieved credentials.",
    "Message1029": "There was a problem while updating retrieved credentials.",
    "Title1030": "Unable to accept connection.",
    "Message1030": "There was a problem while accepting the connection redirection.",
    "Title1031": "Unable to accept connection.",
    "Message1031": "There was a problem while accepting the connection.",
    "Title1032": "Unable to remove credential.",
    "Message1032": "There was a problem while removing the credential.",
    "Title1033": "Unable to fetch credential.",
    "Message1033": "Credential could not be found.",
    "Title1034": "Unable to fetch proof request.",
    "Message1034": "Proof request could not be found.",
    "Title1035": "Unable to fetch credential offer.",
    "Message1035": "Credential offer could not be found.",
    "Title1036": "Unable to fetch wallet credentials",
    "Message1036": "Wallet credentials could not be found",
    "Title1037": "Unable to remove contact.",
    "Message1037": "There was a problem while removing the contact.",
    "Title1038": "Unable to generate a proof request.",
    "Message1038": "There was a problem while generating a proof request.",
  },
  "StatusMessages": {
    "InitAgent": "Initializing agent .."
  },
  "Terms": {
    "TermsOfService": "Terms of Service",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "I Agree",
    "Attestation": "I have read, understand and accept the terms and conditions.",
  },
  "Tour": {
    "GuideTitle": "Welcome to Aries Bifold",
    "WouldYouLike": "Would you like some guidance on how to use Aries Bifold?",
    "UseAppGuides": "Use app guides",
    "DoNotUseAppGuides": "Don't use app guides",
    "AddAndShare": "Add and share credentials",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider.",
    "Notifications": "Notifications",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events.",
    "YourCredentials": "Your credentials",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials.",
    "Skip": "Skip",
    "Next": "Next",
    "Back": "Back",
    "Done": "Done",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Allow camera use",
    "CameraDisclosure": "The camera is used to scan QR codes that initiate a credential offer or credential request. No information about the images is stored, used for analytics, or shared.",
    "ToContinueUsing": "To continue using the Aries Bifold scan feature, please allow camera permissions.",
    "Allow": "Allow",
    "OpenSettings": "Open settings",
  },
  "PINCreate": {
    "Message": {
      "CrossPatternValidation": "A pattern of cross was detected in your PIN. Please try again.",
      "OddOrEvenSequenceValidation": "An odd or even sequence was detected in your PIN. Please try again.",
      "NoRepetitionOfTheSameNumbersValidation": "The PIN can't have a repetition of the same digit. Please try again.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "A repeated two-digit sequence was detected in your PIN. Please try again.",
      "NoSeriesOfNumbersValidation": "A series was detected in your PIN. Please try again.",
      "PINOnlyContainDigitsValidation": "Your PIN needs to only contain digits. Please try again.",
      "PINTooShortValidation": "Your PIN is too short. Please try again.",
      "PINTooLongValidation": "Your PIN is too long. Please try again.",
    },
    "Helper": {
      "CrossPatternValidation": "Does not contain a pattern of cross.",
      "OddOrEvenSequenceValidation": "Does not contain an odd or even sequence.",
      "NoRepetitionOfTheSameNumbersValidation": "Does not contain the same repeating number.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Does not contain repeating two-digit sequence.",
      "NoSeriesOfNumbersValidation": "Does not contain a series of numbers (123).",
      "PINOnlyContainDigitsValidation": "Must contain only digits.",
      "PINTooShortValidation": "The PIN is long enought.",
      "PINTooLongValidation": "The PIN is long enought.",
    },
    "UserAuthenticationPIN": "User authentication PIN",
    "PINTooShort": "PIN is too short",
    "InvalidPIN": "Invalid PIN",
    "PINsDoNotMatch": "PINs do not match",
    "PleaseUseOnlyNumbersInYourPIN": "Please use only numbers in your PIN",
    "YourPINMustBe6DigitsInLength": "Your PIN needs to be 6 digits long.",
    "EnteredPINsDoNotMatch": "The entered PINs do not match. Please try again.",
    "YouNeedToCreateA6DigitPIN": "You need to create a 6 digit PIN",
    "PleaseReenterYourPIN": "Please re-enter your PIN",
    "EnterPINTitle": "Enter a 6 digit PIN",
    "EnterPIN": "Enter PIN",
    "ReenterPIN": "Confirm PIN",
    "ReenterPINTitle": "Re-Enter PIN",
    "CreatePIN": "Create PIN",
    "RememberPIN": "Remember your PIN.",
    "PINDisclaimer": "If you forget it, you will need to set up your wallet again and re-add your cards.",
    "Show": "Show PIN",
    "Hide": "Hide PIN",
    "ChangePIN": "Change PIN",
    "Continue": "Continue",
    "EnterYourCurrentPIN": "Enter your current PIN"
  },
  "PINEnter": {
    "EnterPIN": "Enter your wallet PIN",
    "Unlock": "Unlock",
    "Or": "Or",
    "BiometricsUnlock": "Unlock with biometrics",
    "IncorrectPIN": "Incorrect PIN",
    "RepeatPIN": "Please try your PIN again.",
    "EnableBiometrics": "You have to enable biometrics to be able to load the wallet.",
    "BiometricsNotProvided": "Biometrics not provided, you may use PIN to load the wallet.",
    "BiometricsError": "Biometrics were not successful.",
    "BiometricsErrorEnterPIN": "Please enter your wallet PIN.",
    "LoggedOut": "You're logged out",
    "LoggedOutDescription": "To protect your information, you're logged out of your wallet if you have not used it for 5 minutes.",
    "BiometricsChanged": "Biometrics unlock has been disabled because your device biometrics changed.",
    "BiometricsChangedEnterPIN": "Please enter your wallet PIN.",
    "AttemptLockoutWarning": "Note: for your security, entering another incorrect PIN will temporarily lock the wallet."
  },
  "AttemptLockout": {
    "Title": "Your wallet is temporarily locked",
    "Description": "You have had too many unsuccessful PIN attempts.",
    "TryAgain": "You can try again in:",
    "Hours": "hours",
    "Minutes": "minutes",
    "Seconds": "seconds",
  },
  "Biometry": {
    "Toggle": "Toggle Biometrics",
    "EnabledText1": "Unlock the wallet with your phone's biometrics instead of your wallet PIN.",
    "EnabledText2": "Using biometrics means that all fingerprints or face ID added on this phone will have access to your wallet.",
    "NotEnabledText1": "Biometrics is not currently setup on this device and therefore cannot be enabled.",
    "NotEnabledText2": "If you wish to enable this feature turn biometrics on in the device settings and then return to this screen.",
    "Warning": "Ensure only you have access to your wallet.",
    "UseToUnlock": "Use biometrics to unlock wallet?",
    "UnlockPromptTitle": "Wallet Unlock",
    "UnlockPromptDescription": "Use biometrics to unlock your wallet"
  },
  "Contacts": {
    "EmptyList": "Your wallet is empty. Your connected contacts will be added here.",
    "TypeHere": "Type Message Here",
  },
  "ContactDetails": {
    "Created": "Created",
    "ConnectionState": "Connection State",
    "AContact": "A contact",
    "DateOfConnection": "Date of connection: {{ date }}",
    "RemoveTitle": "Remove this contact",
    "RemoveCaption": "To add credentials, the issuing organization needs to be a contact.",
    "UnableToRemoveTitle": "Unable to remove contact",
    "UnableToRemoveCaption": "Unable to remove because there are credentials issued by this contact in your wallet. Remove the credentials first then remove this contact.",
    "GoToCredentials": "Go to Credentials",
    "ContactRemoved": "Contact removed"
  },
  "WhatAreContacts": {
    "Title": "What are Contacts?",
    "Preamble": "Adding organizations as a Contact will allow you to:",
    "ListItemCredentialUpdates": "Get updates to credentials issued by this organization",
    "ListItemNewCredentials": "Get offered new credentials",
    "ListItemProofRequest": "Fast-track proof requests",
    "RemoveContacts": "You can always remove Contacts at any time from your",
    "ContactsLink": "Contacts list",
    "ContactSharing": "Use of your credentials is never shared with your Contacts."
  },
  "Credentials": {
    "CredentialsNotFound": "Credentials not found",
    "CredentialDetails": "Credential Details",
    "EmptyList": "Your wallet is empty. Your accepted credentials will be added here.",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Created At:",
    "Version": "Version",
    "Issued": "Issued",
    "PrivacyPolicy": "Privacy policy",
    "TermsAndConditions": "Terms and conditions",
    "RemoveFromWallet": "Remove from wallet",
    "Revoked": "Revoked",
    "CredentialRevokedMessageTitle": "This credential is revoked",
    "CredentialRevokedMessageBody": "This credential may no longer work for some proof requests. You will need to update the credential with the issuer.",
    "NewRevoked": "Credential revoked",
    "RemoveTitle": "Remove credential from your wallet",
    "RemoveCaption": "You will lose your ability to prove the information on this credential with this Wallet.",
    "CredentialNotFound": "Credential not found",
    "YouWillNotLose": "You will NOT lose",
    "YouWillNotLoseListItem1": "Your credential within the system that issued you your credential.",
    "YouWillNotLoseListItem2": "The issuing organization as a Contact.",
    "HowToGetThisCredentialBack": "How to get this credential back",
    "HowToGetThisCredentialBackListItem1": "You will have to go to the organization that issued you this credential and request it again.",
    "CredentialRemoved": "Credential removed",
    "IssuedBy": "Issued by:"
  },
  "Home": {
    "Welcome": "Welcome",
    "Notification": "Notification",
    "Notifications": "Notifications",
    "OneNotification": "1 Notification",
    "CountNotifications": "{{ count }} Notifications",
    "NoNewUpdates": "You have no new notifications.",
    "NoCredentials": "You have no credentials in your wallet.",
    "SeeAll": "See all",
    "YouHave": "You have",
    "Credential": "credential",
    "Credentials": "credentials",
    "InYourWallet": "in your wallet"
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Successfully Accepted Connection",
    "AcceptingConnection": "Accepting Connection",
    "ConnectionRecordIdNotFound": "Connection record ID not found",
    "ConnectionAccepted": "Connection Accepted",
    "ConnectionNotFound": "Connection not found",
    "InvalidQrCode": "Invalid QR code. Please try again.",
    "UnableToHandleRedirection": "Unable to handle redirection",
    "Close": "Close",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Just a moment while we make a secure connection...",
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
    "ConnectionInvitation": "Connection Invitation",
    "ScanQR": "Scan this QR Code",
    "ScanQRComment": "with your digital wallet to make a connection.",
    "MakingConnection": "Making connection...",
    "ConnectionCompleted": "Connection completed!",
    "Toggle": "Toggle connection inviter capability",
    "UseConnectionInviterCapability": "Use connection inviter capability?",
    "OpenContact": "Open Contact",
  },
  "ConnectionAlert": {
    "AddedContacts": "Added to Contacts",
    "WhatAreContacts": "What are Contacts?",
    "NotificationBodyUpper": "You can find ",
    "NotificationBodyLower": " in your Contacts. Manage your Contacts in Settings",
    "PopupIntro": "Adding organizations as a contact will allow you to:",
    "PopupPoint1": "Get updates to credentials issued by this organization",
    "PopupPoint2": "Get offered new credentials",
    "PopupPoint3": "Fast-track proof requests",
    "SettingsLink": "Settings",
    "SettingsInstruction": "You can always remove contacts at anytime in ",
    "PrivacyMessage": "Use of your credentials is never shared with your contacts.",
    "PopupExit": "Got it"
  },
  "CredentialOffer": {
    "CredentialOffer": "Credential Offer",
    "ThisIsTakingLongerThanExpected": "This is taking Longer than expected. Check back later for your new credential.",
    "RejectThisCredential?": "Reject this Credential?",
    "AcceptingCredential": "Accepting Credential",
    "SuccessfullyAcceptedCredential": "Successfully Accepted Credential",
    "RejectingCredential": "Rejecting Credential",
    "SuccessfullyRejectedCredential": "Successfully Rejected Credential",
    "CredentialNotFound": "Credential not found",
    "CredentialAccepted": "Credential Accepted",
    "CredentialRejected": "Credential Rejected",
    "CredentialAddedToYourWallet": "Credential added to your wallet",
    "CredentialDeclined": "Credential declined",
    "CredentialOnTheWay": "Your credential is on the way",
    "NewCredentialOffer": "New Credential Offer",
    "IsOfferingYouACredential": "is offering you a credential",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this credential?",
    "ConfirmDeclinedMessage": "In order to receive the credential offer again, you will need to reapply with the issuer.",
    "ConfirmDecline": "Yes, decline this credential",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline Credential",
    "Declined": "Declined",
  },
  "ProofRequest": {
    "ProofRequest": "Proof Request",
    "RequestProcessing": "Just a moment...",
    "OfferDelay": "Offer delay",
    "RejectThisProof?": "Reject this Proof Request?",
    "DeclineThisProof?": "Decline this Proof Request?",
    "AcceptingProof": "Accepting Proof",
    "SuccessfullyAcceptedProof": "Successfully Accepted Proof",
    "ProofRequestNotFound": "Proof request not Found",
    "RejectingProof": "Rejecting Proof",
    "ProofAccepted": "Proof Accepted",
    "ProofRejected": "Proof Rejected",
    "RequestedCredentialsCouldNotBeFound": "Requested credentials could not be found",
    "NewProofRequest": "New Proof Request",
    "NotAvailableInYourWallet": "Not available",
    "IsRequesting": "is requesting",
    "IsRequestingSomethingYouDontHaveAvailable": "is requesting something you don't have available",
    "IsRequestingYouToShare": "is requesting the following information from",
    "Credential": "credential.",
    "Credentials": "credentials.",
    "WhichYouCanProvideFrom": "which you can provide from",
    "Details": "Details",
    "SendingTheInformationSecurely": "Sending the information securely",
    "InformationSentSuccessfully": "Information sent successfully",
    "NewProof": "New Proof",
    "ProofRequestDeclined": "Proof request declined",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this proof request?",
    "ConfirmDeclinedMessage": "In order to receive the proof request again, the requestor will need to resend it.",
    "ConfirmDecline": "Yes, decline this proof request",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline Proof",
    "Declined": "Declined",
    "ShareFollowingInformation_one": "is sharing the following information from {{count}} credential.",
    "ShareFollowingInformation_other": "is sharing the following information from {{count}} credentials."
  },
  "Settings": {
    "Version": "Version",
    "VersionString": "0.0.0-0",
    "AppSettings": "App Settings",
    "AboutApp": "About App",
    "Language": "Language",
    "AppGuides": "App guides",
    "Build": "Build",
    "WhatAreContacts": "What are Contacts?",
    "Help": "Help",
    "MoreInformation": "More information",
    "Developer": "Developer options"
  },
  "TabStack": {
    "Home": "Home",
    "Scan": "Scan",
    "Credentials": "Credentials",
  },
  "RootStack": {
    "Contacts": "Contacts",
    "Settings": "Settings"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permission to use camera",
    "WeNeedYourPermissionToUseYourCamera": "We need your permission to use your camera",
    "Ok": "Ok",
  },
  "QRRender": {
    "GenerationError": "Unable to generate QR code",
  },
  "Record": {
    "Hide": "Hide",
    "Show": "Show",
    "HideAll": "Hide all",
    "Hidden": "Hidden",
    "InvalidDate": "Invalid Date: "
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Onboarding",
    "Terms": "Terms & Conditions",
    "CreatePIN": "Create a PIN",
    "EnterPIN": "Enter PIN",
    "Home": "Home",
    "Scan": "Scan",
    "Credentials": "Credentials",
    "CredentialDetails": "Credential Details",
    "Notifications": "Notifications",
    "CredentialOffer": "Credential Offer",
    "ProofRequest": "Proof Request",
    "ProofRequestDetails": "Proof Request Details",
    "ProofRequestAttributeDetails": "Proof Request Attribute Details",
    "ProofDetails": "Proof Details",
    "Settings": "Settings",
    "Tours": "App guides",
    "Language": "Language",
    "Contacts": "Contacts",
    "Decline": "Decline",
    "ContactDetails": "Contact Details",
    "Biometry": "Biometrics",
    "Developer": "Developer options",
    "ChangePIN": "Change PIN",
    "CommonDecline": "Decline",
    "ProofRequests": "Proof requests",
    "SendProofRequest": "Send a proof request",
    "ChooseProofRequest": "Choose a proof request",
    "ProofRequestUsageHistory": "Usage History",
    "ConnectionInvitation": "Connection Invitation",
    "CreateConnectionInvitation": "Create a connection invitation",
  },
  "Loading": {
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
    "BackToHome": "Go back to home"
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "No internet connection",
    "NoInternetConnectionMessage": "You're unable to access services using Bifold or receive credentials until you're back online.\n\nPlease check your internet connection.",
    "LedgerConnectivityIssueTitle": "Wallet Services",
    "LedgerConnectivityIssueMessage": "A firewall may be preventing you from connecting to wallet related services.",
  },
  "Chat": {
    "OpenItem": "Open",
    "UserYou": "You",
    "CredentialProposalSent": "sent a credential proposal",
    "CredentialOfferReceived": "sent a credential offer",
    "CredentialRequestSent": "sent a credential request",
    "CredentialDeclined": "declined a credential offer",
    "CredentialReceived": "received a credential",
    "ProofRequestSent": "sent a proof request",
    "ProofPresentationReceived": "has sent you information",
    "ProofRequestReceived": "received a proof request",
    "ProofRequestRejected": "rejected a proof request",
    "ProofRequestRejectReceived": "rejected a proof request",
    "ProofRequestSatisfied": "shared information",
  },
  "Verifier": {
    "UseVerifierCapability": "Use Verifier capability?",
    "Toggle": "Toggle Verifier capability",
    "ProcessingProof": "Just a moment...",
    "ZeroKnowledgeProof": "Zero-knowledge proof",
    "Parameterizable": "Parameterizable",
    "GenerateNewQR": "Generate new QR Code",
    "ShareLink": "Share link",
    "ScanQR": "Scan this QR Code",
    "ScanQRComment": "with your digital wallet to receive a proof request.",
    "InformationReceived": "Information received",
    "InformationReceivedDetails": "shared the following information.",
    "ProofVerificationFailed": "Proof verification failed",
    "ViewDetails": "View details",
    "HideDetails": "Hide details",
    "UseProofRequest": "Use this proof request",
    "SendThisProofRequest": "Send this proof request",
    "SendProofRequest": "Send a Proof Request",
    "EmptyList": "Your wallet is empty. Your proof request templates will be added here.",
    "ShowTemplateUsageHistory": "Show usage history",
    "RequestSent": "Presentation request sent",
    "PresentationDeclined": "Presentation request declined",
    "PresentationReceived": "Presentation received",
    "PresentationFailed": "Presentation failed",
    "ProofRequestRejected": "Presentation request rejected",
    "PresentationFrom": "From",
    "PresentationState": "State",
    "ConnectionlessPresentation": "Connectionless",
    'TutorialStep1Title': 'Show this QR code to the other person',
    'TutorialStep1Description': 'You will connect with the other person. They will receive a proof request.',
    "InvalidPredicateValueTitle": "Invalid value for {{ predicate }}",
    "InvalidPredicateValueDetails": "Must be a number",
    "ConnectionLessLabel": "Anonymous"
  }
}

export default translation
