// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Entrar",
    "Submit": "Enviar",
    "NoneYet!": "Nenhuma ainda!",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Accept": "Aceitar",
    "Reject": "Rejeitar",
    "Share": "Compartilhar",
    "Decline": "Recusar",
    "Back": "Voltar",
    "Next": "Próximo",
    "Continue": "Continuar",
    "Info": "Informação",
    "ThisDecisionCannotBeChanged.": "Esta decisão não pode ser alterada.",
    "Failure": "Falha",
    "Success": "Sucesso",
    "SomethingWentWrong": "Algo deu errado",
    "Done": "Feito",
    "Skip": "Pular",
    "View": "Visualizar",
    "Home": "Home",
    "ErrorCode": "Código de Erro",
    "Okay": "OK",
    "GoBack": "Voltar",
    "GetStarted": "Iniciar",
    "Dismiss": "Dispensar",
    "ShowDetails": "Mostrar Detalhes",
    "Biometrics": "Biometria",
    "On": "Ligado",
    "Off": "Desligado",
  },
  "Language": {
    "English": "Inglês",
    "French": "Francês",
    "Portuguese": "Português",
  },
  "Error": {
    "Unknown": "Erro Desconhecido",
    "Problem": "Ocorreu um problema",
    "ErrorCode": "Código de Erro",
    "Title1024": "Não foi possível aceitar oferta de credencial.",
    "Message1024": "Houve um problema ao aceitar a oferta de credencial.",
    "Title1025": "Não foi possível rejeitar oferta de credencial.",
    "Message1025": "Houve um problema ao rejeitar a oferta de credencial.",
    "Title1026": "Não foi possível atualizar credenciais obtidas.",
    "Message1026": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1027": "Não foi possível aceitar requisição de prova.",
    "Message1027": "Houve um problema ao aceitar a requisição de prova.",
    "Title1028": "Não foi possível rejeitar requisição de prova",
    "Message1028": "Houve um problema ao rejeitar a requisição de prova",
    "Title1029": "Detalhes  Não foi possível atualizar credenciais obtidas.",
    "Message1029": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1030": "Não foi possível aceitar conexão.",
    "Message1030": "Houve um problema ao aceitar o redirecionamento de conexão.",
    "Title1031": "Não foi possível aceitar conexão.",
    "Message1031": "Houve um erro ao aceitar a conexão.",
    "Title1032": "Não foi possível remover credencial.",
    "Message1032": "Houve um erro ao remover a credencial.",
    "Title1033": "Não foi possível buscar credencial.",
    "Message1033": "Credencial não foi encontrada.",
    "Title1034": "Não foi possível buscar requisição de prova.",
    "Message1034": "Requisição de prova não foi encontrada.",
    "Title1035": "Não foi possível buscar oferta de credencial.",
    "Message1035": "Oferta de credencial não foi encontrada.",
    "Title1036": "Unable to fetch wallet credentials (PT-BR)",
    "Message1036": "Wallet credentials could not be found (PT-BR)",
    "Title1037": "Unable to remove contact. (PT-BR)",
    "Message1037": "There was a problem while removing the contact. (PT-BR)",
  },
  "StatusMessages": {
    "InitAgent": "Iniciando agente .."
  },
  "Terms": {
    "TermsOfService": "Termos de serviço",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "Eu Concordo",
    "Attestation": "Eu li, entendo e aceito os termos e condições.",
  },
  "PrivacyPolicy": {
    "Title": "Política de Privacidade",
    "CameraDisclosure": "A câmera é usada para escanear QR Codes para processamento imediato no dispositivo. Nenhuma informação sobre as imagens é armazenada, usada para análise, ou compartilhada.",
  },
  "PINCreate": {
    "Message": {
      "CrossPatternValidation": "A pattern of cross was detected in your PIN. Please try again. (PT-BR)",
      "OddOrEvenSequenceValidation": "An odd or even sequence was detected in your PIN. Please try again. (PT-BR)",
      "NoRepetitionOfTheSameNumbersValidation": "The PIN can't have a repetition of the same digit. Please try again. (PT-BR)",
      "NoRepetitionOfTheTwoSameNumbersValidation": "A repeated two-digit sequence was detected in your PIN. Please try again. (PT-BR)",
      "NoSeriesOfNumbersValidation": "A series was detected in your PIN. Please try again. (PT-BR)",
      "PINOnlyContainDigitsValidation": "Your PIN needs to only contain digits. Please try again. (PT-BR)",
      "PINTooShortValidation": "Your PIN is too short. Please try again. (PT-BR)",
      "PINTooLongValidation": "Your PIN is too long. Please try again. (PT-BR)",
    },
    "Helper": {
      "CrossPatternValidation": "Does not contain a pattern of cross. (PT-BR)",
      "OddOrEvenSequenceValidation": "Does not contain an odd or even sequence. (PT-BR)",
      "NoRepetitionOfTheSameNumbersValidation": "Does not contain the same repeating number. (PT-BR)",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Does not contain repeating two-digit sequence. (PT-BR)",
      "NoSeriesOfNumbersValidation": "Does not contain a series of numbers (123). (PT-BR)",
      "PINOnlyContainDigitsValidation": "Must contain only digits. (PT-BR)",
      "PINTooShortValidation": "The PIN is long enought. (PT-BR)",
      "PINTooLongValidation": "The PIN is long enought. (PT-BR)",
    },
    "UserAuthenticationPIN": "PIN de autenticação do usuário",
    "PINTooShort": "PIN é curto demais",
    "InvalidPIN": "PIN inválido",
    "PINsDoNotMatch": "PINs não conferem",
    "PleaseUseOnlyNumbersInYourPIN": "Favor usar somente números em seu PIN",
    "YourPINMustBe6DigitsInLength": "Seu PIN precisa ter 6 digitos.",
    "EnteredPINsDoNotMatch": "Os PINs não conferem. Favor tentar novamente.",
    "YouNeedToCreateA6DigitPIN": "Você precisa criar um PIN de 6 digitos",
    "PleaseReenterYourPIN": "Favor digitar novamente seu PIN",
    "EnterPINTitle": "Digite um PIN de 6 digitos",
    "EnterPIN": "Digitar PIN",
    "ReenterPIN": "Confirmar PIN",
    "ReenterPINTitle": "Digitar novamente PIN",
    "CreatePIN": "Criar PIN",
    "RememberPIN": "Lembre-se do seu PIN.",
    "PINDisclaimer": "Se você o esquecer, você precisará redefinir sua carteira e readicionar seus cards.",
    "Show": "Mostrar PIN",
    "Hide": "Esconder PIN",
    "ChangePIN": "Alterar PIN",
    "Continue": "Continuar",
    "EnterYourCurrentPIN": "Digite seu PIN atual."
  },
  "PINEnter": {
    "EnterPIN": "Digitar PIN",
    "Unlock": "Destravar",
    "Or": "Ou",
    "BiometricsUnlock": "Destravar com Biometria",
    "IncorrectPIN": "PIN incorreto",
    "EnableBiometrics": "Você deve habilitar a biometria para poder carregar a carteira.",
    "BiometricsNotProvided": "Biometria não informada, você deve usar o PIN para carregar a carteira."
  },
  "Biometry": {
    "Toggle": "Habilitar Biometria",
    "EnabledText1": "Destravar a carteira utilizando a biometria de seu telefone ao invés do seu PIN.",
    "EnabledText2": "Usar a biometria significa que todas impressões digitais ou face ID adicionadas neste telefone terão acesso à sua carteira.",
    "NotEnabledText1": "Biometria não está configurada nesse dispositivo e portanto não pode ser habilitada.",
    "NotEnabledText2": "Se você deseja habilitar essa funcionalidade, habilite a biometria nas configurações do dispositivo e então volte para essa tela.",
    "Warning": "Tenha certeza que somente você tem acesso à sua carteira.",
    "UseToUnlock": "Utilizar biometria para destravar a carteira?",
    "NoBiometricsErrorTitle": "Sem biometria",
    "NoBiometricsErrorMessage": "Você não tem biometria habilitada neste dispositivo.",
    "NoBiometricsErrorDetails": "Para arrumar isso, habilite a biometria nas configurações do seu dispositivo.",
    "UnlockPromptTitle": "Destravar carteira",
    "UnlockPromptDescription": "Utilize a biometria para destravar sua carteira"
  },
  "Contacts": {
    "EmptyList": "Sua carteira está vazia. Seus contatos conectados serão adicionados aqui.",
  },
  "ContactDetails": {
    "Created": "Criado",
    "ConnectionState": "Estado da conexão",
    "AContact": "Um contato",
    "DateOfConnection": "Date of connection: {{ date }} (PT-BR)",
    "RemoveTitle": "Remove this contact (PT-BR)",
    "RemoveCaption": "To add credentials, the issuing organization needs to be a contact. (PT-BR)",
    "UnableToRemoveTitle": "Unable to remove contact (PT-BR)",
    "UnableToRemoveCaption": "Unable to remove because there are credentials issued by this contact in your wallet. Remove the credentials first then remove this contact. (PT-BR)",
    "GoToCredentials": "Go to Credentials (PT-BR)",
    "ContactRemoved": "Contact removed (PT-BR)"
  },
  "Credentials": {
    "CredentialsNotFound": "Credenciais não encontradas",
    "CredentialDetails": "Detalhes da Credencial",
    "EmptyList": "Sua carteira está vazia. Suas credenciais aceitas serão adicionadas aqui.",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Criada em:",
    "Version": "Versão",
    "Issued": "Emitida",
    "PrivacyPolicy": "Política de privacidade",
    "TermsAndConditions": "Termos e condições",
    "RemoveFromWallet": "Remover da carteira",
    "Revoked": "Revogada",
    "CredentialRevokedMessageTitle": "Esta credencial está revogada",
    "CredentialRevokedMessageBody": "Esta credencial não funcionará mais para algumas requisições de prova. Voce precisará atualizar a credencial com o emissor.",
    "RemoveTitle": "Remover a credencial da sua carteira",
    "RemoveCaption": "Você perderá a habilidade de prover as informações desta credencial com essa carteira.",
    "CredentialNotFound": "Credencial não encontrada",
    "YouWillNotLose": "Você NÃO perderá",
    "YouWillNotLoseListItem1": "Sua credencial dentro do sistema que lhe emitiu sua credencial.",
    "YouWillNotLoseListItem2": "A organização emissora como um Contato.",
    "HowToGetThisCredentialBack": "Como ter essa credencial de volta",
    "HowToGetThisCredentialBackListItem1": "Você terá que ir à organização que lhe emitiu essa credencial e requisita-la novamente.",
    "CredentialRemoved": "Credencial removida",
    "IssuedBy": "Emitida por:"
  },
  "Home": {
    "Welcome": "Bem Vindo",
    "Notifications": "Notificações",
    "NoNewUpdates": "Você não tem novas notificações.",
    "NoCredentials": "Você não tem credenciais em sua carteira.",
    "SeeAll": "Ver todas",
    "YouHave": "Você tem",
    "Credential": "credencial",
    "Credentials": "credenciais",
    "InYourWallet": "em sua carteira"
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Conexão Aceita com Sucesso",
    "AcceptingConnection": "Aceitando Conexão",
    "ConnectionRecordIdNotFound": "ID de registro de conexão não encontrado",
    "ConnectionAccepted": "Conexão Aceita",
    "ConnectionNotFound": "Conexão Não Encontrada",
    "InvalidQrCode": "QR code inválido. Favor tentar novamente.",
    "UnableToHandleRedirection": "Não foi possível tratar redirecionamento",
    "Close": "Fechar",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Aguarde um momento enquanto fazemos uma conexão segura...",
    "TakingTooLong": "Isto está demorando mais que o normal. Você pode retornar para a home ou continuar esperando."
  },
  "ConnectionAlert": {
    "AddedContacts": "Adicionado aos Contatos",
    "WhatAreContacts": "O que são Contatos?",
    "NotificationBodyUpper": "Voce pode achar ",
    "NotificationBodyLower": " em seus Contatos. Gerenciar seus Contatos em Configurações",
    "PopupIntro": "Adicionar organizações como um contato lhe permitirá que:",
    "PopupPoint1": "Obtenha atualizações de credenciais emitidas por essa organização",
    "PopupPoint2": "Receber novas ofertas de credenciais",
    "PopupPoint3": "Localizar rapidamente requisições de prova",
    "SettingsLink": "Configurações",
    "SettingsInstruction": "Você sempre pode remover contatos a qualquer momento em ",
    "PrivacyMessage": "O uso de suas credenciais nunca é compartilhado com seus contatos.",
    "PopupExit": "Entendi"
  },
  "CredentialOffer": {
    "CredentialOffer": "Oferta de Credencial",
    "ThisIsTakingLongerThanExpected": "Isso está demorando mais que o normal. Verifique novamente mais tarde sua nova credencial.",
    "RejectThisCredential?": "Rejeitar esta credencial?",
    "AcceptingCredential": "Aceitando Credencial",
    "SuccessfullyAcceptedCredential": "Credencial Aceita com Sucesso",
    "RejectingCredential": "Rejeitando Credencial",
    "SuccessfullyRejectedCredential": "Credencial Rejeitada com Sucesso",
    "CredentialNotFound": "Credencial não encontrar",
    "CredentialAccepted": "Credencial Aceita",
    "CredentialRejected": "Credencial Rejeitada",
    "CredentialAddedToYourWallet": "Credencial adicionada à sua carteira",
    "CredentialDeclined": "Credencial recusada",
    "CredentialOnTheWay": "Sua credencial está a caminho",
    "NewCredentialOffer": "Nova Oferta de Credencial",
    "IsOfferingYouACredential": "está lhe oferecendo uma credencial",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta credencial?",
    "ConfirmDeclinedMessage": "Para receber novamente a oferta de credencial, você precisara solicitar novamente ao emissor.",
    "ConfirmDecline": "Sim, recusar esta credencial",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Recusar Credencial",
  },
  "ProofRequest": {
    "ProofRequest": "Requisição de Prova",
    "OfferDelay": "Atrasar oferta",
    "RejectThisProof?": "Rejeitar esta Requisição de Prova?",
    "DeclineThisProof?": "Recusar esta Requisição de Prova?",
    "AcceptingProof": "Aceitando Prova",
    "SuccessfullyAcceptedProof": "Prova Aceita com Sucesso",
    "ProofRequestNotFound": "Requisição de Prova não encontrada.",
    "RejectingProof": "Rejeitando Prova",
    "ProofAccepted": "Prova Aceita",
    "ProofRejected": "Prova Rejeitada",
    "RequestedCredentialsCouldNotBeFound": "Crecenciais requisitadas puderam ser encontradas",
    "NewProofRequest": "Nova Prova de Credencial",
    "NotAvailableInYourWallet": "Não disponível em sua carteira",
    "IsRequesting": "está requisitando",
    "IsRequestingSomethingYouDontHaveAvailable": "está requisitando algo que você não tem disponível",
    "IsRequestingYouToShare": "está requisitando que você compartilhe",
    "WhichYouCanProvideFrom": "que você pode prover de",
    "Details": "Detalhes",
    "SendingTheInformationSecurely": "Enviando a informação de forma segura",
    "InformationSentSuccessfully": "Informação enviada com sucesso",
    "ProofRequestCompleted": "Informação recebida",
    "ProofRequestDeclined": "Requisição de prova recusada",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta requisição de prova?",
    "ConfirmDeclinedMessage": "Para receber a requisição de prova novamente, o requisitante terá de reenvia-la.",
    "ConfirmDecline": "Sim, recusar esta requisição de prova",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Recusar Prova",
  },
  "Settings": {
    "Version": "Versão",
    "VersionString": "0.0.0-0",
    "AppSettings": "Configurações do Aplicativo",
    "AboutApp": "Sobre o App",
    "Language": "Idioma",
    "WhatAreContacts": "O que são Contatos?",
    "Developer": "Developer options"
  },
  "TabStack": {
    "Home": "Home",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
  },
  "RootStack": {
    "Contacts": "Contatos",
    "Settings": "Configurações"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permissão para usar a câmera",
    "WeNeedYourPermissionToUseYourCamera": "Precisamos de sua permissão para usar sua câmera",
    "Ok": "Ok",
  },
  "Record": {
    "Hide": "Esconder",
    "Show": "Mostrar",
    "HideAll": "Esconder todos",
    "Hidden": "Escondido"
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Onboarding",
    "Terms": "Termos & Condições",
    "CreatePIN": "Criar um PIN",
    "EnterPIN": "Digitar o PIN",
    "Home": "Home",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
    "CredentialDetails": "Detalhes de Credencial",
    "Notifications": "Notificações",
    "CredentialOffer": "Oferta de Credencial",
    "ProofRequest": "Requisição de Prova",
    "ProofRequestAttributeDetails": "Atributos de Requisição de Prova",
    "Settings": "Configurações",
    "Language": "Idioma",
    "Contacts": "Contatos",
    "Decline": "Recusar",
    "ContactDetails": "Detalhes do Contato",
    "Biometry": "Biometria",
    "Developer": "Developer options",
    "ChangePIN": "Alterar PIN",
  },
  "Loading": {
    "TakingTooLong": "Isso esta demorando mais que o normal. Você pode voltar para a home ou continuar esperando.",
    "BackToHome": "Voltar para a home"
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Sem conexão com a internet",
    "NoInternetConnectionMessage": "Não é possivel acessar serviços utilizando a Bifold ou receber credenciais até você voltar a estar online.\n\nFavor checkar sua conexão com a internet.",
    "LedgerConnectivityIssueTitle": "Wallet Services (pt-BR)",
    "LedgerConnectivityIssueMessage": "A firewall may be preventing you from connecting to wallet related services. (pt-BR)",
  }
}

export default translation
