// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Enter",
    "Submit": "Submit",
    "NoneYet!": "None yet!",
    "Cancel": "Cancel",
    "Confirm": "Confirm",
    "Accept": "Accept",
    "Reject": "Reject",
    "Share": "Share",
    "Decline": "Decline",
    "Back": "Back",
    "Next": "Next",
    "Continue": "Continue",
    "Info": "Information",
    "ThisDecisionCannotBeChanged.": "This decision cannot be changed.",
    "Failure": "Failure",
    "Success": "Success",
    "SomethingWentWrong": "Something went wrong",
    "Done": "Done",
    "Skip": "Skip",
    "View": "View",
    "Home": "Home",
    "ErrorCode": "Error Code",
    "Okay": "Okay",
    "GoBack": "Go Back",
    "GetStarted": "Get Started",
    "Dismiss": "Dismiss",
    "ShowDetails": "Show Details",
  },
  "Language": {
    "English": "English",
    "French": "French",
  },
  "Error": {
    "Unknown": "Unknown Error",
    "Problem": "A problem has occurred",
    "ErrorCode": "Error code",
    "Title1024": "Unable to accept credential offer.",
    "Message1024": "There was a problem while accepting the credential offer.",
    "Title1025": "Unable to reject credential offer",
    "Message1025": "There was a problem while rejecting the credential offer",
    "Title1026": "Unable to update retrieved credentials.",
    "Message1026": "There was a problem while updating retrieved credentials.",
    "Title1027": "Unable to accept proof request.",
    "Message1027": "There was a problem while accepting the proof request.",
    "Title1028": "Unable to reject proof request",
    "Message1028": "There was a problem while rejecting the proof request",
    "Title1029": "Details	Unable to update retrieved credentials.",
    "Message1029": "There was a problem while updating retrieved credentials.",
    "Title1030": "Unable to accept connection.",
    "Message1030": "There was a problem while accepting the connection redirection.",
    "Title1031": "Unable to accept connection.",
    "Message1031": "There was a problem while accepting the connection.",
    "Title1032": "Unable to remove credential.",
    "Message1032": "There was a problem while removing the credential.",
    "Title1033": "Unable to fetch credential.",
    "Message1033": "Credential could not be found."
  },
  "StatusMessages": {
    "InitAgent": "Initializing agent .."
  },
  "Terms": {
    "TermsOfService": "Terms of Service",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "I Agree",
    "Attestation": "I have read, understand and accept the terms and conditions.",
  },
  "PinCreate": {
    "UserAuthenticationPIN": "User authentication PIN",
    "PINTooShort": "PIN too short",
    "InvalidPIN": "Invalid PIN",
    "PINsDoNotMatch": "PINs do not match",
    "PleaseUseOnlyNumbersInYourPIN": "Please use only numbers in your PIN",
    "YourPINMustBe6DigitsInLength": "Your PIN must be six digits in length",
    "EnteredPINsDoNotMatch": "The entered PINs do not match. Please try again.",
    "YouNeedToCreateA6DigitPIN": "You need to create a 6 digit PIN",
    "PleaseReenterYourPIN": "Please re-enter your PIN",
    "EnterPINTitle": "Enter a 6 digit PIN",
    "EnterPIN": "Enter PIN",
    "ReenterPIN": "Confirm PIN",
    "ReenterPINTitle": "Re-Enter PIN",
    "CreatePIN": "Create PIN",
    "RememberPIN": "Remember your PIN.",
    "PINDisclaimer": "If you forget it, you will need to set up your wallet again and re-add your cards.",
    "Show": "Show",
    "Hide": "Hide",
  },
  "PinEnter": {
    "EnterPIN": "Enter PIN",
    "IncorrectPIN": "Incorrect PIN",
  },
  "Contacts": {
    "EmptyList": "Your wallet is empty. Your connected contacts will be added here.",
  },
  "ContactDetails": {
    "Created": "Created",
    "ConnectionState": "Connection State",
    "AContact": "A contact",
  },
  "Credentials": {
    "CredentialsNotFound": "Credentials not found",
    "CredentialDetails": "Credential Details",
    "EmptyList": "Your wallet is empty. Your accepted credentials will be added here.",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Created At:",
    "Version": "Version",
    "Issued": "Issued",
    "PrivacyPolicy": "Privacy policy",
    "TermsAndConditions": "Terms and conditions",
    "RemoveFromWallet": "Remove from wallet",
    "Revoked": "Revoked",
    "CredentialRevokedMessageTitle": "This credential is revoked",
    "CredentialRevokedMessageBody": "This credential may no longer work for some proof requests. You will need to update the credential with the issuer.",
    "RemoveTitle": "Remove credential from your wallet",
    "RemoveCaption": "You will lose your ability to prove the information on this credential with BC Wallet.",
    "CredentialNotFound": "Credential not found",
    "YouWillNotLose": "You will NOT lose",
    "YouWillNotLoseListItem1": "Your credential within the system that issued you your credential.",
    "YouWillNotLoseListItem2": "The issuing organization as a Contact.",
    "HowToGetThisCredentialBack": "How to get this credential back",
    "HowToGetThisCredentialBackListItem1": "You will have to go to the organization that issued you this credential and request it again.",
    "CredentialRemoved": "Credential removed",
  },
  "Home": {
    "Welcome": "Welcome",
    "Notifications": "Notifications",
    "NoNewUpdates": "You have no new notifications.",
    "NoCredentials": "You have no credentials in your wallet.",
    "SeeAll": "See all",
    "YouHave": "You have",
    "Credential": "credential",
    "Credentials": "credentials",
    "InYourWallet": "in your wallet"
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Successfully Accepted Connection",
    "AcceptingConnection": "Accepting Connection",
    "ConnectionRecordIdNotFound": "Connection record ID not found",
    "ConnectionAccepted": "Connection Accepted",
    "ConnectionNotFound": "Connection not found",
    "InvalidQrCode": "Invalid QR code. Please try again.",
    "UnableToHandleRedirection": "Unable to handle redirection",
    "Close": "Close",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Just a moment while we make a secure connection...",
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting."
  },
  "CredentialOffer": {
    "CredentialOffer": "Credential Offer",
    "ThisIsTakingLongerThanExpected": "This is taking Longer than expected. Check back later for your new credential.",
    "RejectThisCredential?": "Reject this Credential?",
    "AcceptingCredential": "Accepting Credential",
    "SuccessfullyAcceptedCredential": "Successfully Accepted Credential",
    "RejectingCredential": "Rejecting Credential",
    "SuccessfullyRejectedCredential": "Successfully Rejected Credential",
    "CredentialNotFound": "Credential not found",
    "CredentialAccepted": "Credential Accepted",
    "CredentialRejected": "Credential Rejected",
    "CredentialAddedToYourWallet": "Credential added to your wallet",
    "CredentialDeclined": "Credential declined",
    "CredentialOnTheWay": "Your credential is on the way",
    "NewCredentialOffer": "New Credential Offer",
    "IsOfferingYouACredential": "is offering you a credential",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this credential?",
    "ConfirmDeclinedMessage": "In order to receive the credential offer again, you will need to reapply with the issuer.",
    "ConfirmDecline": "Yes, decline this credential",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline Credential",
  },
  "ProofRequest": {
    "ProofRequest": "Proof Request",
    "OfferDelay": "Offer delay",
    "RejectThisProof?": "Reject this Proof Request?",
    "DeclineThisProof?": "Decline this Proof Request?",
    "AcceptingProof": "Accepting Proof",
    "SuccessfullyAcceptedProof": "Successfully Accepted Proof",
    "ProofNotFound": "Proof not Found",
    "RejectingProof": "Rejecting Proof",
    "ProofAccepted": "Proof Accepted",
    "ProofRejected": "Proof Rejected",
    "RequestedCredentialsCouldNotBeFound": "Requested credentials could not be found",
    "NewProofRequest": "New Proof Request",
    "NotAvailableInYourWallet": "Not available in your wallet",
    "IsRequesting": "is requesting",
    "IsRequestingSomethingYouDontHaveAvailable": "is requesting something you don't have available",
    "IsRequestingYouToShare": "is requesting you to share",
    "WhichYouCanProvideFrom": "which you can provide from",
    "Details": "Details",
    "SendingTheInformationSecurely": "Sending the information securely",
    "InformationSentSuccessfully": "Information sent successfully",
    "ProofRequestCompleted": "Information approved",
    "ProofRequestDeclined": "Proof request declined",
    "ConfirmDeclinedTitle": "Are you sure you want to decline this proof request?",
    "ConfirmDeclinedMessage": "In order to receive the proof request again, the requestor will need to resend it.",
    "ConfirmDecline": "Yes, decline this proof request",
    "AbortDecline": "No, go back",
    "DeclineTitle": "Decline Proof",
  },
  "Settings": {
    "Version": "Version",
    "VersionString": "0.0.0-0",
    "AppPreferences": "App Preferences",
    "AboutApp": "About App",
    "Language": "Language",
  },
  "TabStack": {
    "Home": "Home",
    "Scan": "Scan",
    "Credentials": "Credentials",
  },
  "RootStack": {
    "Contacts": "Contacts",
    "Settings": "Settings"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permission to use camera",
    "WeNeedYourPermissionToUseYourCamera": "We need your permission to use your camera",
    "Ok": "Ok",
  },
  "Record": {
    "Hide": "Hide",
    "Show": "Show",
    "HideAll": "Hide all",
    "Hidden": "Hidden"
  },
  "Screens": {
    "Splash": 'Splash',
    "Onboarding": "Onboarding",
    "Terms": "Terms & Conditions",
    "CreatePin": 'Create a PIN',
    "EnterPin": 'Enter PIN',
    "Home": 'Home',
    "Scan": 'Scan',
    "Credentials": 'Credentials',
    "CredentialDetails": 'Credential Details',
    "Notifications": 'Notifications',
    "CredentialOffer": 'Credential Offer',
    "ProofRequest": 'Proof Request',
    "ProofRequestAttributeDetails": 'Proof Request Attribute Details',
    "Settings": 'Settings',
    "Language": 'Language',
    "Contacts": 'Contacts',
    "ContactDetails": 'Contact Details',
  },
  "Loading": {
    "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
    "BackToHome": "Go back to home"
  }
}

export default translation
