// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Entrar",
    "Submit": "Enviar",
    "NoneYet!": "Nenhuma ainda!",
    "Save": "Save (PB)",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Accept": "Aceitar",
    "Reject": "Rejeitar",
    "NotNow": "Agora não",
    "Share": "Compartilhar",
    "Decline": "Recusar",
    "Back": "Voltar",
    "Next": "Próximo",
    "Continue": "Continuar",
    "Info": "Informação",
    "ThisDecisionCannotBeChanged.": "Esta decisão não pode ser alterada.",
    "Failure": "Falha",
    "Success": "Sucesso",
    "SomethingWentWrong": "Algo deu errado",
    "Done": "Feito",
    "Skip": "Pular",
    "View": "Visualizar",
    "Home": "Home",
    "ErrorCode": "Código de Erro",
    "Okay": "OK",
    "GoBack": "Voltar",
    "GetStarted": "Iniciar",
    "Dismiss": "Dispensar",
    "ShowDetails": "Mostrar Detalhes",
    "Biometrics": "Biometria",
    "On": "Ligado",
    "Off": "Desligado",
    "Close": "Fechar",
    "Remove": "Remover",
  },
  "Date": {
    "ShortFormat": "D MMM",
    "LongFormat": "D MMMM",
    "MonthLong": {
      "January": "janeiro",
      "February": "fevereiro",
      "March": "março",
      "April": "abril",
      "May": "maio",
      "June": "junho",
      "July": "julho",
      "August": "agosto",
      "September": "setembro",
      "October": "outubro",
      "November": "novembro",
      "December": "dezembro",
    },
    "MonthShort": {
      "January": "jan",
      "February": "fev",
      "March": "março",
      "April": "abril",
      "May": "maio",
      "June": "junho",
      "July": "julho",
      "August": "agosto",
      "September": "set",
      "October": "out",
      "November": "nov",
      "December": "dez",
    },
    "MinuteAgo": "minuto atrás",
    "MinutesAgo": "minutos atrás",
    "JustNow": "Agora",
  },
  "Language": {
    "code_en": "Inglês",
    "code_fr": "Francês",
    "code_pt-BR": "Português",
  },
  "Error": {
    "Unknown": "Erro Desconhecido",
    "Problem": "Ocorreu um problema",
    "ErrorCode": "Código de Erro",
    "Title1024": "Não foi possível aceitar oferta de credencial.",
    "Message1024": "Houve um problema ao aceitar a oferta de credencial.",
    "Title1025": "Não foi possível rejeitar oferta de credencial.",
    "Message1025": "Houve um problema ao rejeitar a oferta de credencial.",
    "Title1026": "Não foi possível atualizar credenciais obtidas.",
    "Message1026": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1027": "Não foi possível aceitar requisição de prova.",
    "Message1027": "Houve um problema ao aceitar a requisição de prova.",
    "Title1028": "Não foi possível rejeitar requisição de prova",
    "Message1028": "Houve um problema ao rejeitar a requisição de prova",
    "Title1029": "Detalhes  Não foi possível atualizar credenciais obtidas.",
    "Message1029": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1030": "Não foi possível aceitar conexão.",
    "Message1030": "Houve um problema ao aceitar o redirecionamento de conexão.",
    "Title1031": "Não foi possível aceitar conexão.",
    "Message1031": "Houve um erro ao aceitar a conexão.",
    "Title1032": "Não foi possível remover credencial.",
    "Message1032": "Houve um erro ao remover a credencial.",
    "Title1033": "Não foi possível buscar credencial.",
    "Message1033": "Credencial não foi encontrada.",
    "Title1034": "Não foi possível buscar requisição de prova.",
    "Message1034": "Requisição de prova não foi encontrada.",
    "Title1035": "Não foi possível buscar oferta de credencial.",
    "Message1035": "Oferta de credencial não foi encontrada.",
    "Title1036": "Não foi possível obter credenciais da carteira",
    "Message1036": "Não foram encontradas credenciais na carteira",
    "Title1037": "Não foi possível remover Contato",
    "Message1037": "Ocorreu um problema ao remover o Contato",
    "Title1038": "Não foi possível gerar uma solicitação de prova",
    "Message1038": "Ocorreu um problema ao gerar uma solicitação de prova.",
    "Title1039": "Unable to handle deeplink. (PT-BR)",
    "Message1039": "There was a problem while handling a deeplink. (PT-BR)",
    "Title1040": "Unable to create PIN. (PT-BR)",
    "Message1040": "There was a problem while creating the PIN. (PT-BR)",
    "Title1041": "Unable to unlock with PIN. (PT-BR)",
    "Message1041": "There was a problem while unlocking with PIN. (PT-BR)",
    "Title1042": "Unable to verify PIN. (PT-BR)",
    "Message1042": "There was a problem while verifying the PIN. (PT-BR)",
    "Title1043": "Unable to retrieve credentials for proof. (PT-BR)",
    "Message1043": "There was a problem while retrieving credentials for the proof. (PT-BR)",
    "Title1044": "Unable to initialize onboarding. (PT-BR)",
    "Message1044": "There was a problem while initializing onboarding. (PT-BR)",
    "Title1045": "Unable to initialize agent. (PT-BR)",
    "Message1045": "There was a problem while initializing agent. (PT-BR)",
  },
  "StatusMessages": {
    "InitAgent": "Iniciando agente .."
  },
  "Terms": {
    "TermsOfService": "Termos de serviço",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "Eu Concordo",
    "Attestation": "Eu li, entendo e aceito os termos e condições.",
  },
  "Tour": {
    "GuideTitle": "Bem-vindo a Aries Bifold",
    "WouldYouLike": "Gostaria de ver algumas instruções sobre como usar a Aries Bifold?",
    "UseAppGuides": "Usar o guia do app",
    "DoNotUseAppGuides": "Não usar o guia do app",
    "AddAndShare": "Adicionar e compartilhar credenciais",
    "AddAndShareDescription": "Para adicionar e usar credenciais voce scaneia um QR code exibido pelo provedor de serviço.",
    "AddCredentials": "Adicionar credenciais",
    "AddCredentialsDescription": "Adicione credenciais escaneando um QR code exibido no serviço do emissor",
    "Notifications": "Notificações",
    "NotificationsDescription": "Depois de scanear um QR code, a oferta de credencial ou requisição de prova irá aparecer aqui, assim como outros eventos",
    "YourCredentials": "Suas credenciais",
    "YourCredentialsDescription": "Suas credenciais digitais adicionadas aparecem aqui. Você pode ver os detalhes da credencial e adicionar ou remover credenciais.",
    "CredentialOffers": "Ofertas de credencial",
    "CredentialOffersDescription": "Uma organização ter ofereceu uma credencial. Revise os detalhes da credencial e escolha aceita-la o rejeita-la. Credenciais aceitas serão adicionadas a sua carteira.",
    "ProofRequests": "Requisições de prova",
    "ProofRequestsDescription": "Uma organização está pedindo que você prove suas credenciais. Revise o que eles estão pedindo e escolha por aceitar o rejeitar esta requisição.",
    "Skip": "Pular",
    "Next": "Próximo",
    "Back": "Voltar",
    "Done": "Terminar",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Permitir uso da câmera",
    "CameraDisclosure": "A câmera é usada para escanear QR Codes para processamento imediato no dispositivo. Nenhuma informação sobre as imagens é armazenada, usada para análise, ou compartilhada.",
    "ToContinueUsing": "Para continuar usando a funcionalidade de scan da Aries Bifold, favor permitir o uso da câmera.",
    "OpenSettings": "Abrir as configurações",
  },
  "PINCreate": {
    "Message": {
      "CrossPatternValidation": "Um padrão de X foi detectado no seu PIN. Favor tentar novamente.",
      "OddOrEvenSequenceValidation": "Uma sequencia de números pares ou ímpares foi detectada em seu PIN. Favor tentar novamente.",
      "NoRepetitionOfTheSameNumbersValidation": "O PIN não pode ter a repetição de um mesmo número. Favor tentar novamente.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Uma sequência repetida de dois números foi detectada em seu PIN. Favor tentar novamente.",
      "NoSeriesOfNumbersValidation": "Uma sequência foi detectada em seu PIN. Favor tentar novamente.",
      "PINOnlyContainDigitsValidation": "Seu PIN deve conter apenas números. Favor tentar novamente.",
      "PINTooShortValidation": "Seu PIN é muito curto. Favor tentar novamente.",
      "PINTooLongValidation": "Seu PIN é muito longo. Favor tentar novamente.",
    },
    "Helper": {
      "CrossPatternValidation": "Não contém um padrão de X.",
      "OddOrEvenSequenceValidation": "Não contém uma sequência de números pares ou ímpares.",
      "NoRepetitionOfTheSameNumbersValidation": "Não contém o mesmo número repetido.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Não contém uma sequência repetida de dois números.",
      "NoSeriesOfNumbersValidation": "Não contém uma sequência de números (123).",
      "PINOnlyContainDigitsValidation": "Deve conter apenas números.",
      "PINTooShortValidation": "O PIN é curto demais.",
      "PINTooLongValidation": "O PIN é longo demais.",
    },
    "UserAuthenticationPIN": "PIN de autenticação do usuário",
    "PINTooShort": "PIN é curto demais",
    "InvalidPIN": "PIN inválido",
    "PINsDoNotMatch": "PINs não conferem",
    "PleaseUseOnlyNumbersInYourPIN": "Favor usar somente números em seu PIN",
    "YourPINMustBe6DigitsInLength": "Seu PIN precisa ter 6 digitos.",
    "EnteredPINsDoNotMatch": "Os PINs não conferem. Favor tentar novamente.",
    "YouNeedToCreateA6DigitPIN": "Você precisa criar um PIN de 6 digitos",
    "PleaseReenterYourPIN": "Favor digitar novamente seu PIN",
    "PinChangeSuccessTitle": "Seu PIN foi alterado com sucesso",
    "PinChangeSuccessMessage": "Seu PIN foi alterado com sucesso. Agora voce pode entrar no app com seu novo PIN.",
    "EnterOldPINTitle": "Digite seu PIN antigo",
    "NewPIN": "novo",
    "EnterPINTitle": "Digite um {{ new }}PIN de 6 digitos",
    "EnterPIN": "Digitar PIN",
    "ReenterPIN": "Digite novamente o {{ new }}PIN",
    "ReenterPINTitle": "Digitar novamente PIN",
    "CreatePIN": "Criar PIN",
    "RememberPIN": "Criar um PIN para assegurar sua carteira.",
    "RememberChangePIN": "Altere seu PIN para assegurar sua carteira.",
    "PINDisclaimer": "Se você o esquecer, você precisará redefinir sua carteira e readicionar seus cards.",
    "Show": "Mostrar PIN",
    "Hide": "Esconder PIN",
    "ChangePIN": "Alterar PIN",
    "Continue": "Continuar",
    "EnterYourCurrentPIN": "Digite seu PIN atual."
  },
  "PINEnter": {
    "EnterPIN": "Digitar PIN",
    "Unlock": "Destravar",
    "Or": "Ou",
    "BiometricsUnlock": "Destravar com Biometria",
    "IncorrectPIN": "PIN incorreto",
    "EnableBiometrics": "Você deve habilitar a biometria para poder carregar a carteira.",
    "BiometricsNotProvided": "Biometria não informada, você deve usar o PIN para carregar a carteira.",
    "BiometricsError": "Biometrics were not successful.",
    "BiometricsErrorEnterPIN": "Please enter your wallet PIN."
  },
  "Biometry": {
    "Toggle": "Habilitar Biometria",
    "EnabledText1": "Destravar a carteira utilizando a biometria de seu telefone ao invés do seu PIN.",
    "EnabledText2": "Usar a biometria significa que todas impressões digitais ou face ID adicionadas neste telefone terão acesso à sua carteira.",
    "NotEnabledText1": "Biometria não está configurada nesse dispositivo e portanto não pode ser habilitada.",
    "NotEnabledText2": "Se você deseja habilitar essa funcionalidade, habilite a biometria nas configurações do dispositivo e então volte para essa tela.",
    "Warning": "Tenha certeza que somente você tem acesso à sua carteira.",
    "UseToUnlock": "Utilizar biometria para destravar a carteira?",
    "NoBiometricsErrorTitle": "Sem biometria",
    "NoBiometricsErrorMessage": "Você não tem biometria habilitada neste dispositivo.",
    "NoBiometricsErrorDetails": "Para arrumar isso, habilite a biometria nas configurações do seu dispositivo.",
    "UnlockPromptTitle": "Destravar carteira",
    "UnlockPromptDescription": "Utilize a biometria para destravar sua carteira"
  },
  "Contacts": {
    "EmptyList": "Seus Contatos esta vazio!",
    "TypeHere": "Enviar mensagem para este contato...",
    "PeopleAndOrganizations": "Pessoas e organizações com as quais você interagiu estão listadas aqui.",
    "WhatAreContacts": "O que são Contatos?",
    "AddContact": "Adicionar um Contato",
  },
  "ContactDetails": {
    "Created": "Criado",
    "ConnectionState": "Estado da conexão",
    "AContact": "Um Contato",
    "DateOfConnection": "Data da conexão: {{ date }}",
    "RemoveTitle": "Remover este Contato",
    "RemoveCaption": "Para adicionar credenciais, a organização emissora deve ser um Contato.",
    "UnableToRemoveTitle": "Não foi possível remover o Contato.",
    "UnableToRemoveCaption": "Não foi possivel remover pois há credenciais emitidas por este Contato em sua carteira. Remove essas credenciais antes e então remova este Contato.",
    "GoToCredentials": "Ir para Credenciais.",
    "RemoveContact": "Remover Contato",
    "ContactRemoved": "Contato removido",
    "RemoveContactMessageTop": "Ao remover este Contato você não podera mais:",
    "RemoveContactMessageBottom": "Este Contato não será notificado que você o removeu de seus Contatos",
    "RemoveContactsBulletPoint1": "Mensagens diretas para este Contato",
    "RemoveContactsBulletPoint2": "Ter novas credenciais ofertadas por este Contato",
    "RemoveContactsBulletPoint3": "Ser notificado de atualizações de suas credenciais emitidas por esse Contato",
    "RemoveContactsBulletPoint4": "Requisitar informações deste Contato ou este requisitar informações suas",
  },
  "WhatAreContacts": {
    "Title": "O que são Contatos?",
    "Preamble": "Contatos são pessoas ou organizações com as quais você tem interagido\n\nVocês são conectados por um meio seguro e privado que ninguem senão você ou eles podem ver. Nada é compartilhado sem sua permissão.\n\nVoce pode:",
    "ListItemDirectMessage": "Enviar mensagens diretas para seus Contatos",
    "ListItemNewCredentials": "Receba ofertas de novas credenciais.",
    "ListItemNotifiedOfUpdates": "Ser notificado de atualizações de suas credenciais emitidas por eles",
    "ListItemRequest": "Requisitar infgormações de seus Contatos ou estes requisitar informações suas",
    "RemoveContacts": "Você sempre pode remover Contatos a qualquer momento de sua",
    "ContactsLink": "Lista de Contatos",
  },
  "Credentials": {
    "CredentialsNotFound": "Credenciais não encontradas",
    "CredentialDetails": "Detalhes da Credencial",
    "EmptyList": "Sua carteira está vazia. Suas credenciais aceitas serão adicionadas aqui.",
    "IssuedBy": "Emitida por",
    "Credential": "credencial"
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Criada em:",
    "Version": "Versão",
    "Issued": "Emitida",
    "PrivacyPolicy": "Política de privacidade",
    "TermsAndConditions": "Termos e condições",
    "RemoveFromWallet": "Remover da carteira",
    "Revoked": "Revogada",
    "CredentialRevokedMessageTitle": "Esta credencial está revogada",
    "CredentialRevokedMessageBody": "Esta credencial não funcionará mais para algumas requisições de prova. Voce precisará atualizar a credencial com o emissor.",
    "NewRevoked": "Credencial revogada",
    "RemoveTitle": "Remover a credencial da sua carteira",
    "RemoveCaption": "Você perderá a habilidade de prover as informações desta credencial com essa carteira.",
    "CredentialNotFound": "Credencial não encontrada",
    "YouWillNotLose": "Você NÃO perderá",
    "YouWillNotLoseListItem1": "Sua credencial dentro do sistema que lhe emitiu sua credencial.",
    "YouWillNotLoseListItem2": "A organização emissora como um Contato.",
    "HowToGetThisCredentialBack": "Como ter essa credencial de volta",
    "HowToGetThisCredentialBackListItem1": "Você terá que ir à organização que lhe emitiu essa credencial e requisita-la novamente.",
    "CredentialRemoved": "Credencial removida",
    "IssuedBy": "Emitida por:",
    "RemoveCredential": "Remover Credencial",
  },
  "Home": {
    "Welcome": "Bem Vindo",
    "Notifications": "Notificações",
    "NoNewUpdates": "Você não tem novas notificações.",
    "NoCredentials": "Você não tem credenciais em sua carteira.",
    "SeeAll": "Ver todas",
    "YouHave": "Você tem",
    "Credential": "credencial",
    "Credentials": "credenciais",
    "InYourWallet": "em sua carteira",
    "NewMessage": "New message (PT-BR)",
    "SentMessage": "sent a message (PT-BR)",
    "ReceivedMessage": "You received a new message (PT-BR)",
    "ViewMessage": "View message (PT-BR)",
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Conexão Aceita com Sucesso",
    "AcceptingConnection": "Aceitando Conexão",
    "ConnectionRecordIdNotFound": "ID de registro de conexão não encontrado",
    "ConnectionAccepted": "Conexão Aceita",
    "ConnectionNotFound": "Conexão Não Encontrada",
    "InvalidQrCode": "QR code inválido. Favor tentar novamente.",
    "WillScanAutomatically": "Um QR code válido será escaneado automaticamente.",
    "ScanQRCode": "Scanear QR code",
    "MyQRCode": "Meu QR code",
    "UnableToHandleRedirection": "Não foi possível tratar redirecionamento",
    "Close": "Fechar",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Aguarde um momento enquanto fazemos uma conexão segura...",
    "TakingTooLong": "Isto está demorando mais que o normal. Você pode retornar para a home ou continuar esperando.",
    "ConnectionInvitation": "Convite de conexão",
    "ScanQR": "Show this QR code to the other person",
    "ScanQRComment": "Depois que um QR code é scaneado, uma conexão será criada.",
    "ShareQR": "Compartilhar este QR code com alguém irá adicioná-lo como um Contato.",
    "MakingConnection": "Fazendo conexão...",
    "ConnectionCompleted": "Conexão concluída!",
    "Toggle": "Alternar capacidade de convite de conexão",
    "UseConnectionInviterCapability": "Usar o recurso de convite de conexão?",
    "OpenContact": "Contato aberto",
  },
  "ConnectionAlert": {
    "AddedContacts": "Adicionado aos Contatos",
    "WhatAreContacts": "O que são Contatos?",
    "NotificationBodyUpper": "Voce pode achar ",
    "NotificationBodyLower": " em seus Contatos. Gerenciar seus Contatos em Configurações",
    "PopupIntro": "Adicionar organizações como um Contato lhe permitirá que:",
    "PopupPoint1": "Obtenha atualizações de credenciais emitidas por essa organização",
    "PopupPoint2": "Receber novas ofertas de credenciais",
    "PopupPoint3": "Localizar rapidamente requisições de prova",
    "SettingsLink": "Configurações",
    "SettingsInstruction": "Você sempre pode remover Contatos a qualquer momento em ",
    "PrivacyMessage": "O uso de suas credenciais nunca é compartilhado com seus Contatos.",
    "PopupExit": "Entendi"
  },
  "CredentialOffer": {
    "CredentialOffer": "Oferta de Credencial",
    "ThisIsTakingLongerThanExpected": "Isso está demorando mais que o normal. Verifique novamente mais tarde sua nova credencial.",
    "RejectThisCredential?": "Rejeitar esta credencial?",
    "AcceptingCredential": "Aceitando Credencial",
    "SuccessfullyAcceptedCredential": "Credencial Aceita com Sucesso",
    "RejectingCredential": "Rejeitando Credencial",
    "SuccessfullyRejectedCredential": "Credencial Rejeitada com Sucesso",
    "CredentialNotFound": "Credencial não encontrar",
    "CredentialAccepted": "Credencial Aceita",
    "CredentialRejected": "Credencial Rejeitada",
    "CredentialAddedToYourWallet": "Credencial adicionada à sua carteira",
    "CredentialDeclined": "Credencial recusada",
    "CredentialOnTheWay": "Sua credencial está a caminho",
    "NewCredentialOffer": "Nova Oferta de Credencial",
    "IsOfferingYouACredential": "está lhe oferecendo uma credencial",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta credencial?",
    "ConfirmDeclinedMessage": "Para receber novamente a oferta de credencial, você precisara solicitar novamente ao emissor.",
    "ConfirmDecline": "Sim, recusar esta credencial",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Recusar oferta de credencial?",
    "Declined": "Recusado",
    "ReviewSentInformation_one": "Você compartilhou as seguites informações de {{count}} credencial com",
    "ReviewSentInformation_other": "Você compartilhou as seguites informações de {{count}} credenciais com",
    "ShareFollowingInformation_one": "está compartilhando as seguintes informações de credenciais {{count}}.",
    "ShareFollowingInformation_other": "está compartilhando as seguintes informações de credenciais {{count}}.",
    "DeclineParagraph1": "Para receber novamente a oferta de credencial, você precisara iniciar novamente o processo de emissão com o serviço emissor.",
    "DeclineParagraph2": "Você tem certeza que quer recusar esta oferta de credencial?",
    "CustomOfferTitle": "Remover esta oferta?",
    "CustomOfferParagraph1": "Remover esta oferta irá remover a notificação de sua lista.",
    "CustomOfferParagraph2": "Não reconhece a organização. Verifique sua lista de Contatos. Você só recebe notificões de Contatos que você tenha adicionado.",
  },
  "ProofRequest": {
    "FromYourWallet": "From your wallet (PB)",
    "MissingCredentials": "Missing credentials (PB)",
    "PredicateGeDate": "é posterior a",
    "PredicateLeDate": "é anterior a",
    "PredicateGe": "é maior ou igual a",
    "PredicateGr": "é maior que",
    "PredicateLe": "é menor ou igual a",
    "PredicateLs": "é menor que",
    "ProofRequest": "Requisição de Prova",
    "RequestProcessing": "Só um momento...",
    "OfferDelay": "Atrasar oferta",
    "ChangeCredential": "Escolher credencial",
    "RejectThisProof?": "Rejeitar esta Requisição de Prova?",
    "DeclineThisProof?": "Recusar esta Requisição de Prova?",
    "AcceptingProof": "Aceitando Prova",
    "MultipleCredentials": "Você tem múltiplas credenciais para escolher:",
    "SuccessfullyAcceptedProof": "Prova Aceita com Sucesso",
    "SensitiveInformation": "This request is asking for sensitive information. (PB)",
    "ProofRequestNotFound": "Requisição de Prova não encontrada.",
    "RejectingProof": "Rejeitando Prova",
    "ProofAccepted": "Prova Aceita",
    "ProofRejected": "Prova Rejeitada",
    "RequestedCredentialsCouldNotBeFound": "Crecenciais requisitadas puderam ser encontradas",
    "NewProofRequest": "Nova Prova de Credencial",
    "NotAvailableInYourWallet": "Não disponível em sua carteira",
    "PredicateNotSatisfied": "Requisito não atendido",
    "IsRequesting": "está requisitando",
    "IsRequestingSomethingYouDontHaveAvailable": "está requisitando algo que você não tem disponível",
    "YouDoNotHaveDataPredicate": "Você não atende aos requisitos deste pedido de prova solicitado por",
    "IsRequestingYouToShare": "está requisitando a seguinte informação de",
    "Credential": "credencial.",
    "Credentials": "credenciais.",
    "WhichYouCanProvideFrom": "que você pode prover de",
    "Details": "Detalhes",
    "SendingTheInformationSecurely": "Enviando a informação de forma segura",
    "InformationSentSuccessfully": "Informação enviada com sucesso",
    "ProofRequestCompleted": "Informação recebida",
    "ProofRequestDeclined": "Requisição de prova recusada",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta requisição de prova?",
    "ConfirmDeclinedMessage": "Para receber a requisição de prova novamente, o requisitante terá de reenvia-la.",
    "ConfirmDecline": "Sim, recusar esta requisição de prova",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Recusar requisição de prova?",
    "Declined": "Recusado",
    "DeclineBulletPoint1": "Organizações e serviços requerem que você prove que é elegível para continuar com os serviços ou acessos delas.",
    "DeclineBulletPoint2": "Para obter a requisição de prova novamente, voce precisará iniciar novamente o processo com o serviço.",
    "DeclineBulletPoint3": "Você tem certeza que quer recusar esta requisição de prova?",
  },
  "Settings": {
    "Version": "Versão",
    "VersionString": "0.0.0-0",
    "AppSettings": "Configurações do Aplicativo",
    "AboutApp": "Sobre o App",
    "ChangePin": "Alterar o PIN",
    "Language": "Idioma",
    "DataRetention": "Retenção de dados",
    "PreventAutoLock": "Prevenir travamento automático",
    "TogglePreventAutoLock": "Alternar prevenir travamento automático",
    "AppGuides": "Guia do app",
    "WhatAreContacts": "O que são Contatos?",
    "ScanMyQR": "Scanear meu QR code",
    "Developer": "Opções de Desenvolvedor"
  },
  "TabStack": {
    "Home": "Notificações",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
  },
  "RootStack": {
    "Contacts": "Contatos",
    "Settings": "Configurações"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permissão para usar a câmera",
    "WeNeedYourPermissionToUseYourCamera": "Precisamos de sua permissão para usar sua câmera",
    "Ok": "Ok",
  },
  "QRRender": {
    "GenerationError": "Não foi possível gerar o código QR",
  },
  "Record": {
    "Hide": "Esconder",
    "Show": "Mostrar",
    "HideAll": "Esconder todos",
    "ShowAll": "Mostrar tudos",
    "Hidden": "Escondido",
    "Zoom": "Zoom",
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Onboarding",
    "Preface": "Aries Bifold",
    "Terms": "Termos & Condições",
    "CreatePIN": "Criar um PIN",
    "EnterPIN": "Digitar o PIN",
    "Home": "Notificações",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
    "CredentialDetails": "Detalhes de Credencial",
    "Notifications": "Notificações",
    "CredentialOffer": "Oferta de Credencial",
    "ProofRequest": "Requisição de Prova",
    "ProofChangeCredential": "Escolha uma credencial",
    "ProofRequestDetails": "Detalhes Da Solicitação De Comprovação",
    "ProofRequestAttributeDetails": "Atributos de Requisição de Prova",
    "ProofDetails": "Detalhes da prova",
    "Settings": "Configurações",
    "Language": "Idioma",
    "DataRetention": "Retenção de dados",
    "Tours": "Guias do app",
    "Contacts": "Contatos",
    "Decline": "Recusar",
    "ContactDetails": "Detalhes do Contato",
    "Biometry": "Biometria",
    "Developer": "Developer options",
    "ChangePIN": "Alterar PIN",
    "ProofRequests": "Solicitações de prova",
    "SendProofRequest": "Envie um pedido de prova",
    "ChooseProofRequest": "Escolha um pedido de prova",
    "ProofRequestUsageHistory": "Histórico de uso",
    "CreateConnectionInvitation": "Criar um convite de conexão",
    "NameWallet": "Nomear sua carteira",
    "RenameContact": "Edit Contact Name (PT-BR)",
  },
  "Loading": {
    "TakingTooLong": "Isso esta demorando mais que o normal. Você pode voltar para a home ou continuar esperando.",
    "BackToHome": "Voltar para a home"
  },
  "NameWallet": {
    "EnableWalletNaming": "Habilitar nome da carteira?",
    "ToggleWalletNaming": "Alternar nome da carteira",
    "NameYourWallet": "Nome da sua carteira",
    "EditWalletName": "Edit wallet name (PT-BR)",
    "ThisIsTheName": "Este é o nome que as pessoas verão quando se conectar a você.",
    "CharCountTitle": "Número de caracteres excedido",
    "CharCountDescription": "Voce excedeu o numer máximo de 50 caracteres. Por favor, reduza o número de caracteres.",
    "EmptyNameTitle": "O nome de sua carteira não pode ser vazio",
    "EmptyNameDescription": "Este é o nome que as pessoas verão quando se conerctar a você. Por favor, digite o nome da carteira.",
  },
  "RenameContact": {
    "ThisContactName": "This contact name is only displayed in your Contacts List. (PT-BR)",
    "ContactName": "Contact name (PT-BR)",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Sem conexão com a internet",
    "NoInternetConnectionMessage": "Não é possivel acessar serviços utilizando a Bifold ou receber credenciais até você voltar a estar online.\n\nFavor checkar sua conexão com a internet.",
    "LedgerConnectivityIssueTitle": "Serviços de Carteira",
    "LedgerConnectivityIssueMessage": "Um firewall pode estar te impedindo de conectar-se a serviços relacionados a carteira.",
  },
  "Onboarding": {
    "SkipA11y": "Pular introdução a Aries Bifold",
  },
  "Preface": {
    "PrimaryHeading": "Is this app for you? (PT-BR)",
    "Paragraph1": "Most people will not have a need for Aries Bifold because very few digital credentials are currently available. (PT-BR)",
    "Confirmed": "I have confirmed that this app is for me. (PT-BR)",
  },
  "Chat": {
    "OpenPresentation": "Abrir apresentação",
    "ViewRequest": "Ver requisição",
    "ViewOffer": "Ver oferta",
    "OpenItem": "Abrir",
    "UserYou": "Você",
    "YouConnected": "Você se conectou com",
    "CredentialProposalSent": "enviou uma proposta de credencial",
    "CredentialOfferReceived": "enviou uma oferta de credencial",
    "CredentialRequestSent": "enviou uma solicitação de credencial",
    "CredentialDeclined": "recusou uma oferta de credencial",
    "CredentialReceived": "recebeu uma credencial",
    "ProofRequestSent": "enviou uma solicitação de prova",
    "ProofPresentationReceived": "te enviou informações",
    "ProofRequestReceived": "recebeu uma solicitação de prova",
    "ProofRequestRejected": "rejeitou uma solicitação de prova",
    "ProofRequestRejectReceived": "rejeitou um pedido de prova",
    "ProofRequestSatisfied": "informações compartilhadas",
  },
  "Verifier": {
    "UseVerifierCapability": "Usar o recurso Verificador?",
    "AcceptDevCredentials": "Aceitar credenciais que não sejam de produção",
    "UseDevVerifierTemplates": "Usar templates de verificador de desenvolvimento?",
    "Toggle": "Alternar capacidade do verificador",
    "ToggleDevTemplates": "Alternar Templates de Verificador de Desenvolvimento",
    "ProcessingProof": "Um momento...",
    "ZeroKnowledgeProof": "Prova de conhecimento Zero",
    "Parameterizable": "Parametrizável",
    "RefreshQR": "Atualizar QR Code",
    "GenerateNewQR": "Requisitar outra prova",
    "ShareLink": "Compartilhar link",
    "ScanQR": "Mostrar este QR code para a outra pessoa",
    "ScanQRComment": "Depois do QR code ser scaneado, a requisição de prova será enviada.",
    "InformationReceived": "Informação recebida.",
    "InformationReceivedDetails": "Revisar a informação abaixo.",
    "ProofVerificationFailed": "A verificação da prova falhou",
    "ViewDetails": "Ver detalhes",
    "HideDetails": "Detalhes ocultos",
    "UseProofRequest": "Envie d'une sollicitation de compromis",
    "SendThisProofRequest": "Envie esta solicitação de prova",
    "SendProofRequest": "Envie uma Solicitação de Comprovante",
    "EmptyList": "Sua carteira está vazia. Seus modelos de solicitação de prova serão adicionados aqui.",
    "ShowTemplateUsageHistory": "Mostrar histórico de uso",
    "RequestSent": "Pedido de apresentação enviado",
    "PresentationDeclined": "Pedido de apresentação recusado",
    "PresentationReceived": "Apresentação recebida",
    "PresentationFailed": "Falha na apresentação",
    "ProofRequestRejected": "Pedido de apresentação rejeitado",
    "PresentationFrom": "De",
    "PresentationState": "Estada",
    "ConnectionlessPresentation": "Sem conexão",
    'TutorialStep1Title': 'Mostrar este código QR para a outra pessoa',
    'TutorialStep1Description': 'Você se conectará com a outra pessoa. Eles receberão uma solicitação de prova.',
    "InvalidPredicateValueTitle": "Valor inválido para {{ predicate }}",
    "InvalidPredicateValueDetails": "Deve ser um número",
    "ConnectionLessLabel": "Anônimo"
  }
}

export default translation
