// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Entrar",
    "Submit": "Enviar",
    "NoneYet!": "Nenhuma ainda!",
    "Cancel": "Cancelar",
    "Confirm": "Confirmar",
    "Accept": "Aceitar",
    "Reject": "Rejeitar",
    "NotNow": "Agora não",
    "Share": "Compartilhar",
    "Decline": "Recusar",
    "Back": "Voltar",
    "Next": "Próximo",
    "Continue": "Continuar",
    "Info": "Informação",
    "ThisDecisionCannotBeChanged.": "Esta decisão não pode ser alterada.",
    "Failure": "Falha",
    "Success": "Sucesso",
    "SomethingWentWrong": "Algo deu errado",
    "Done": "Feito",
    "Skip": "Pular",
    "View": "Visualizar",
    "Home": "Home",
    "ErrorCode": "Código de Erro",
    "Okay": "OK",
    "GoBack": "Voltar",
    "GetStarted": "Iniciar",
    "Dismiss": "Dispensar",
    "ShowDetails": "Mostrar Detalhes",
    "Biometrics": "Biometria",
    "On": "Ligado",
    "Off": "Desligado",
    "Close": "Close (PB)",
    "Remove": "Remove (PB)",
  },
  "Date": {
    "ShortFormat": "D MMM YYYY",
    "LongFormat": "D MMMM YYYY, HH:mm:ss",
    "MonthLong": {
      "January": "janeiro",
      "February": "fevereiro",
      "March": "março",
      "April": "abril",
      "May": "maio",
      "June": "junho",
      "July": "julho",
      "August": "agosto",
      "September": "setembro",
      "October": "outubro",
      "November": "novembro",
      "December": "dezembro",
    },
    "MonthShort": {
      "January": "jan",
      "February": "fev",
      "March": "março",
      "April": "abril",
      "May": "maio",
      "June": "junho",
      "July": "julho",
      "August": "agosto",
      "September": "set",
      "October": "out",
      "November": "nov",
      "December": "dez",
    }
  },
  "Language": {
    "English": "Inglês",
    "French": "Francês",
    "Portuguese": "Português",
  },
  "Error": {
    "Unknown": "Erro Desconhecido",
    "Problem": "Ocorreu um problema",
    "ErrorCode": "Código de Erro",
    "Title1024": "Não foi possível aceitar oferta de credencial.",
    "Message1024": "Houve um problema ao aceitar a oferta de credencial.",
    "Title1025": "Não foi possível rejeitar oferta de credencial.",
    "Message1025": "Houve um problema ao rejeitar a oferta de credencial.",
    "Title1026": "Não foi possível atualizar credenciais obtidas.",
    "Message1026": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1027": "Não foi possível aceitar requisição de prova.",
    "Message1027": "Houve um problema ao aceitar a requisição de prova.",
    "Title1028": "Não foi possível rejeitar requisição de prova",
    "Message1028": "Houve um problema ao rejeitar a requisição de prova",
    "Title1029": "Detalhes  Não foi possível atualizar credenciais obtidas.",
    "Message1029": "Houve um problema ao atualizar as credenciais obtidas.",
    "Title1030": "Não foi possível aceitar conexão.",
    "Message1030": "Houve um problema ao aceitar o redirecionamento de conexão.",
    "Title1031": "Não foi possível aceitar conexão.",
    "Message1031": "Houve um erro ao aceitar a conexão.",
    "Title1032": "Não foi possível remover credencial.",
    "Message1032": "Houve um erro ao remover a credencial.",
    "Title1033": "Não foi possível buscar credencial.",
    "Message1033": "Credencial não foi encontrada.",
    "Title1034": "Não foi possível buscar requisição de prova.",
    "Message1034": "Requisição de prova não foi encontrada.",
    "Title1035": "Não foi possível buscar oferta de credencial.",
    "Message1035": "Oferta de credencial não foi encontrada.",
    "Title1036": "Não foi possível obter credenciais da carteira",
    "Message1036": "Não foram encontradas credenciais na carteira",
    "Title1037": "Não foi possível remover Contato",
    "Message1037": "Ocorreu um problema ao remover o Contato",
    "Title1038": "Não foi possível gerar uma solicitação de prova",
    "Message1038": "Ocorreu um problema ao gerar uma solicitação de prova.",
  },
  "StatusMessages": {
    "InitAgent": "Iniciando agente .."
  },
  "Terms": {
    "TermsOfService": "Termos de serviço",
    "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
    "IAgree": "Eu Concordo",
    "Attestation": "Eu li, entendo e aceito os termos e condições.",
  },
  "Tour": {
    "GuideTitle": "Welcome to Aries Bifold (PT-BR)",
    "WouldYouLike": "Would you like some guidance on how to use Aries Bifold? (PT-BR)",
    "UseAppGuides": "Use app guides (PT-BR)",
    "DoNotUseAppGuides": "Don't use app guides (PT-BR)",
    "AddAndShare": "Add and share credentials (PT-BR)",
    "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider. (PT-BR)",
    "Notifications": "Notifications (PT-BR)",
    "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events. (PT-BR)",
    "YourCredentials": "Your credentials (PT-BR)",
    "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials. (PT-BR)",
    "Skip": "Skip (PT-BR)",
    "Next": "Next (PT-BR)",
    "Back": "Back (PT-BR)",
    "Done": "Done (PT-BR)",
  },
  "CameraDisclosure": {
    "AllowCameraUse": "Permitir uso da câmera",
    "CameraDisclosure": "A câmera é usada para escanear QR Codes para processamento imediato no dispositivo. Nenhuma informação sobre as imagens é armazenada, usada para análise, ou compartilhada.",
    "ToContinueUsing": "Para continuar usando a funcionalidade de scan da Aries Bifold, favor permitir o uso da câmera.",
    "Allow": "Permitir",
    "OpenSettings": "Abrir as configurações",
  },
  "PINCreate": {
    "Message": {
      "CrossPatternValidation": "Um padrão de X foi detectado no seu PIN. Favor tentar novamente.",
      "OddOrEvenSequenceValidation": "Uma sequencia de números pares ou ímpares foi detectada em seu PIN. Favor tentar novamente.",
      "NoRepetitionOfTheSameNumbersValidation": "O PIN não pode ter a repetição de um mesmo número. Favor tentar novamente.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Uma sequência repetida de dois números foi detectada em seu PIN. Favor tentar novamente.",
      "NoSeriesOfNumbersValidation": "Uma sequência foi detectada em seu PIN. Favor tentar novamente.",
      "PINOnlyContainDigitsValidation": "Seu PIN deve conter apenas números. Favor tentar novamente.",
      "PINTooShortValidation": "Seu PIN é muito curto. Favor tentar novamente.",
      "PINTooLongValidation": "Seu PIN é muito longo. Favor tentar novamente.",
    },
    "Helper": {
      "CrossPatternValidation": "Não contém um padrão de X.",
      "OddOrEvenSequenceValidation": "Não contém uma sequência de números pares ou ímpares.",
      "NoRepetitionOfTheSameNumbersValidation": "Não contém o mesmo número repetido.",
      "NoRepetitionOfTheTwoSameNumbersValidation": "Não contém uma sequência repetida de dois números.",
      "NoSeriesOfNumbersValidation": "Não contém uma sequência de números (123).",
      "PINOnlyContainDigitsValidation": "Deve conter apenas números.",
      "PINTooShortValidation": "O PIN é curto demais.",
      "PINTooLongValidation": "O PIN é longo demais.",
    },
    "UserAuthenticationPIN": "PIN de autenticação do usuário",
    "PINTooShort": "PIN é curto demais",
    "InvalidPIN": "PIN inválido",
    "PINsDoNotMatch": "PINs não conferem",
    "PleaseUseOnlyNumbersInYourPIN": "Favor usar somente números em seu PIN",
    "YourPINMustBe6DigitsInLength": "Seu PIN precisa ter 6 digitos.",
    "EnteredPINsDoNotMatch": "Os PINs não conferem. Favor tentar novamente.",
    "YouNeedToCreateA6DigitPIN": "Você precisa criar um PIN de 6 digitos",
    "PleaseReenterYourPIN": "Favor digitar novamente seu PIN",
    "EnterPINTitle": "Digite um PIN de 6 digitos",
    "EnterPIN": "Digitar PIN",
    "ReenterPIN": "Re-enter PIN (PT-BR)",
    "ReenterPINTitle": "Digitar novamente PIN",
    "CreatePIN": "Criar PIN",
    "RememberPIN": "Create a PIN to secure your wallet. (PT-BR)",
    "PINDisclaimer": "Se você o esquecer, você precisará redefinir sua carteira e readicionar seus cards.",
    "Show": "Mostrar PIN",
    "Hide": "Esconder PIN",
    "ChangePIN": "Alterar PIN",
    "Continue": "Continuar",
    "EnterYourCurrentPIN": "Digite seu PIN atual."
  },
  "PINEnter": {
    "EnterPIN": "Digitar PIN",
    "Unlock": "Destravar",
    "Or": "Ou",
    "BiometricsUnlock": "Destravar com Biometria",
    "IncorrectPIN": "PIN incorreto",
    "EnableBiometrics": "Você deve habilitar a biometria para poder carregar a carteira.",
    "BiometricsNotProvided": "Biometria não informada, você deve usar o PIN para carregar a carteira.",
    "BiometricsError": "Biometrics were not successful.",
    "BiometricsErrorEnterPIN": "Please enter your wallet PIN."
  },
  "Biometry": {
    "Toggle": "Habilitar Biometria",
    "EnabledText1": "Destravar a carteira utilizando a biometria de seu telefone ao invés do seu PIN.",
    "EnabledText2": "Usar a biometria significa que todas impressões digitais ou face ID adicionadas neste telefone terão acesso à sua carteira.",
    "NotEnabledText1": "Biometria não está configurada nesse dispositivo e portanto não pode ser habilitada.",
    "NotEnabledText2": "Se você deseja habilitar essa funcionalidade, habilite a biometria nas configurações do dispositivo e então volte para essa tela.",
    "Warning": "Tenha certeza que somente você tem acesso à sua carteira.",
    "UseToUnlock": "Utilizar biometria para destravar a carteira?",
    "NoBiometricsErrorTitle": "Sem biometria",
    "NoBiometricsErrorMessage": "Você não tem biometria habilitada neste dispositivo.",
    "NoBiometricsErrorDetails": "Para arrumar isso, habilite a biometria nas configurações do seu dispositivo.",
    "UnlockPromptTitle": "Destravar carteira",
    "UnlockPromptDescription": "Utilize a biometria para destravar sua carteira"
  },
  "Contacts": {
    "EmptyList": "Your Contacts is empty! (PT-BR)",
    "TypeHere": "Type Message Here (PT-BR)",
    "PeopleAndOrganizations": "People and organizations you've interacted with are listed here. (PT-BR)",
    "WhatAreContacts": "What are Contacts? (PT-BR)",
    "AddContact": "Add Contact (PT-BR)",
  },
  "ContactDetails": {
    "Created": "Criado",
    "ConnectionState": "Estado da conexão",
    "AContact": "Um Contato",
    "DateOfConnection": "Data da conexão: {{ date }}",
    "RemoveTitle": "Remover este Contato",
    "RemoveCaption": "Para adicionar credenciais, a organização emissora deve ser um Contato.",
    "UnableToRemoveTitle": "Não foi possível remover o Contato.",
    "UnableToRemoveCaption": "Não foi possivel remover pois há credenciais emitidas por este Contato em sua carteira. Remove essas credenciais antes e então remova este Contato.",
    "GoToCredentials": "Ir para Credenciais.",
    "RemoveContact": "Remove Contact (PT-BR)",
    "ContactRemoved": "Contato removido",
    "RemoveContactMessageTop": "By removing this Contact you'll no longer be able to: (PT-BR)",
    "RemoveContactMessageBottom": "This Contact will not be notified that you removed them from your Contacts (PT-BR)",
    "RemoveContactsBulletPoint1": "Direct message this Contact (PT-BR)",
    "RemoveContactsBulletPoint2": "Get offered new credentials from this Contact (PT-BR)",
    "RemoveContactsBulletPoint3": "Get notified of updates to your credentials issued by this Contact (PT-BR)",
    "RemoveContactsBulletPoint4": "Request for information from this Contact or they request information from you (PT-BR)",
  },
  "WhatAreContacts": {
    "Title": "O que são Contatos?",
    "Preamble": "Contacts are people or organizations you've interacted with.\n\nYou're connected over a secure and private line that no one but you or them can see. Nothing is shared without your permission.\n\nYou can: (PR-BR)",
    "ListItemDirectMessage": "Direct message your Contacts (PT-BR)",
    "ListItemNewCredentials": "Receba ofertas de novas credenciais.",
    "ListItemNotifiedOfUpdates": "Get notified of updates to your credentials issued by them (PT-BR)",
    "ListItemRequest": "Request for information from your Contact or they request information from you (PT-BR)",
    "RemoveContacts": "Você sempre pode remover Contatos a qualquer momento de sua",
    "ContactsLink": "Lista de Contatos",
  },
  "Credentials": {
    "CredentialsNotFound": "Credenciais não encontradas",
    "CredentialDetails": "Detalhes da Credencial",
    "EmptyList": "Sua carteira está vazia. Suas credenciais aceitas serão adicionadas aqui.",
    "IssuedBy": "Issued by (PT-BR)",
    "Credential": "credential (PT-BR)"
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Criada em:",
    "Version": "Versão",
    "Issued": "Emitida",
    "PrivacyPolicy": "Política de privacidade",
    "TermsAndConditions": "Termos e condições",
    "RemoveFromWallet": "Remover da carteira",
    "Revoked": "Revogada",
    "CredentialRevokedMessageTitle": "Esta credencial está revogada",
    "CredentialRevokedMessageBody": "Esta credencial não funcionará mais para algumas requisições de prova. Voce precisará atualizar a credencial com o emissor.",
    "NewRevoked": "Credential revoked (PT-BR)",
    "RemoveTitle": "Remover a credencial da sua carteira",
    "RemoveCaption": "Você perderá a habilidade de prover as informações desta credencial com essa carteira.",
    "CredentialNotFound": "Credencial não encontrada",
    "YouWillNotLose": "Você NÃO perderá",
    "YouWillNotLoseListItem1": "Sua credencial dentro do sistema que lhe emitiu sua credencial.",
    "YouWillNotLoseListItem2": "A organização emissora como um Contato.",
    "HowToGetThisCredentialBack": "Como ter essa credencial de volta",
    "HowToGetThisCredentialBackListItem1": "Você terá que ir à organização que lhe emitiu essa credencial e requisita-la novamente.",
    "CredentialRemoved": "Credencial removida",
    "IssuedBy": "Emitida por:",
    "RemoveCredential": "Remove Credential (PT-BR)",
  },
  "Home": {
    "Welcome": "Bem Vindo",
    "Notifications": "Notificações",
    "NoNewUpdates": "Você não tem novas notificações.",
    "NoCredentials": "Você não tem credenciais em sua carteira.",
    "SeeAll": "Ver todas",
    "YouHave": "Você tem",
    "Credential": "credencial",
    "Credentials": "credenciais",
    "InYourWallet": "em sua carteira"
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Conexão Aceita com Sucesso",
    "AcceptingConnection": "Aceitando Conexão",
    "ConnectionRecordIdNotFound": "ID de registro de conexão não encontrado",
    "ConnectionAccepted": "Conexão Aceita",
    "ConnectionNotFound": "Conexão Não Encontrada",
    "InvalidQrCode": "QR code inválido. Favor tentar novamente.",
    "WillScanAutomatically": "A valid QR code will scan automatically. (PT-BR)",
    "ScanQRCode": "Scan QR code (PT-BR)",
    "MyQRCode": "My QR code (PT-BR)",
    "UnableToHandleRedirection": "Não foi possível tratar redirecionamento",
    "Close": "Fechar",
    "Torch": "Flash"
  },
  "Connection": {
    "JustAMoment": "Aguarde um momento enquanto fazemos uma conexão segura...",
    "TakingTooLong": "Isto está demorando mais que o normal. Você pode retornar para a home ou continuar esperando.",
    "ConnectionInvitation": "Convite de conexão",
    "ScanQR": "Show this QR code to the other person",
    "ScanQRComment": "After the QR code is scanned, a connection will be created. (PB)",
    "ShareQR": "Sharing this QR code with someone will add them as a Contact. (PT-BR)",
    "MakingConnection": "Fazendo conexão...",
    "ConnectionCompleted": "Conexão concluída!",
    "Toggle": "Alternar capacidade de convite de conexão",
    "UseConnectionInviterCapability": "Usar o recurso de convite de conexão?",
    "OpenContact": "Contato aberto",
  },
  "ConnectionAlert": {
    "AddedContacts": "Adicionado aos Contatos",
    "WhatAreContacts": "O que são Contatos?",
    "NotificationBodyUpper": "Voce pode achar ",
    "NotificationBodyLower": " em seus Contatos. Gerenciar seus Contatos em Configurações",
    "PopupIntro": "Adicionar organizações como um Contato lhe permitirá que:",
    "PopupPoint1": "Obtenha atualizações de credenciais emitidas por essa organização",
    "PopupPoint2": "Receber novas ofertas de credenciais",
    "PopupPoint3": "Localizar rapidamente requisições de prova",
    "SettingsLink": "Configurações",
    "SettingsInstruction": "Você sempre pode remover Contatos a qualquer momento em ",
    "PrivacyMessage": "O uso de suas credenciais nunca é compartilhado com seus Contatos.",
    "PopupExit": "Entendi"
  },
  "CredentialOffer": {
    "CredentialOffer": "Oferta de Credencial",
    "ThisIsTakingLongerThanExpected": "Isso está demorando mais que o normal. Verifique novamente mais tarde sua nova credencial.",
    "RejectThisCredential?": "Rejeitar esta credencial?",
    "AcceptingCredential": "Aceitando Credencial",
    "SuccessfullyAcceptedCredential": "Credencial Aceita com Sucesso",
    "RejectingCredential": "Rejeitando Credencial",
    "SuccessfullyRejectedCredential": "Credencial Rejeitada com Sucesso",
    "CredentialNotFound": "Credencial não encontrar",
    "CredentialAccepted": "Credencial Aceita",
    "CredentialRejected": "Credencial Rejeitada",
    "CredentialAddedToYourWallet": "Credencial adicionada à sua carteira",
    "CredentialDeclined": "Credencial recusada",
    "CredentialOnTheWay": "Sua credencial está a caminho",
    "NewCredentialOffer": "Nova Oferta de Credencial",
    "IsOfferingYouACredential": "está lhe oferecendo uma credencial",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta credencial?",
    "ConfirmDeclinedMessage": "Para receber novamente a oferta de credencial, você precisara solicitar novamente ao emissor.",
    "ConfirmDecline": "Sim, recusar esta credencial",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Decline credential offer? (PB-BR)",
    "Declined": "Recusado",
    "ReviewSentInformation_one": "(PB) You shared the following information from {{count}} credential with",
    "ReviewSentInformation_other": "(PB) You shared the following information from {{count}} credentials with",
    "ShareFollowingInformation_one": "está compartilhando as seguintes informações de credenciais {{count}}.",
    "ShareFollowingInformation_other": "está compartilhando as seguintes informações de credenciais {{count}}.",
    "DeclineParagraph1": "In order to receive the credential offer again, you will need to restart the issuing process again with the issuing service. (PB-BR)",
    "DeclineParagraph2": "Are you sure you want to decline this credential offer? (PB-BR)",
    "CustomOfferTitle": "Delete this offer? (PB-BR)",
    "CustomOfferParagraph1": "Deleting this offer will remove the notification from your list. (PB-BR)",
    "CustomOfferParagraph2": "Don't recongize the organization? Check your Contact list. you only recieve notifications from Contacts you've initiated. (PB-BR)"
  },
  "ProofRequest": {
    "ProofRequest": "Requisição de Prova",
    "RequestProcessing": "Só um momento...",
    "OfferDelay": "Atrasar oferta",
    "RejectThisProof?": "Rejeitar esta Requisição de Prova?",
    "DeclineThisProof?": "Recusar esta Requisição de Prova?",
    "AcceptingProof": "Aceitando Prova",
    "SuccessfullyAcceptedProof": "Prova Aceita com Sucesso",
    "ProofRequestNotFound": "Requisição de Prova não encontrada.",
    "RejectingProof": "Rejeitando Prova",
    "ProofAccepted": "Prova Aceita",
    "ProofRejected": "Prova Rejeitada",
    "RequestedCredentialsCouldNotBeFound": "Crecenciais requisitadas puderam ser encontradas",
    "NewProofRequest": "Nova Prova de Credencial",
    "NotAvailableInYourWallet": "Não disponível em sua carteira",
    "IsRequesting": "está requisitando",
    "IsRequestingSomethingYouDontHaveAvailable": "está requisitando algo que você não tem disponível",
    "IsRequestingYouToShare": "is requesting the following information from",
    "Credential": "credential.",
    "Credentials": "credentials.",
    "WhichYouCanProvideFrom": "que você pode prover de",
    "Details": "Detalhes",
    "SendingTheInformationSecurely": "Enviando a informação de forma segura",
    "InformationSentSuccessfully": "Informação enviada com sucesso",
    "ProofRequestCompleted": "Informação recebida",
    "ProofRequestDeclined": "Requisição de prova recusada",
    "ConfirmDeclinedTitle": "Você tem certeza que quer recusar esta requisição de prova?",
    "ConfirmDeclinedMessage": "Para receber a requisição de prova novamente, o requisitante terá de reenvia-la.",
    "ConfirmDecline": "Sim, recusar esta requisição de prova",
    "AbortDecline": "Não, voltar",
    "DeclineTitle": "Decline proof request? (PB-BR)",
    "Declined": "Recusado",
    "DeclineBulletPoint1": "Organizations and services require that you prove you're eligible to continue with their service or access. (PB-BR)",
    "DeclineBulletPoint2": "In order to receive the proof request again, you will need to restart the process with the service. (PB-BR)",
    "DeclineBulletPoint3": "Are you sure you want to decline this proof request? (PB-BR)",  
  },
  "Settings": {
    "Version": "Versão",
    "VersionString": "0.0.0-0",
    "AppSettings": "Configurações do Aplicativo",
    "AboutApp": "Sobre o App",
    "Language": "Idioma",
    "AppGuides": "App guides (PT-BR)",
    "WhatAreContacts": "O que são Contatos?",
    "ScanMyQR": "Scan my QR code (PT-BR)",
    "Developer": "Developer options"
  },
  "TabStack": {
    "Home": "Home",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
  },
  "RootStack": {
    "Contacts": "Contatos",
    "Settings": "Configurações"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Permissão para usar a câmera",
    "WeNeedYourPermissionToUseYourCamera": "Precisamos de sua permissão para usar sua câmera",
    "Ok": "Ok",
  },
  "QRRender": {
    "GenerationError": "Não foi possível gerar o código QR",
  },
  "Record": {
    "Hide": "Esconder",
    "Show": "Mostrar",
    "HideAll": "Esconder todos",
    "ShowAll": "Mostrar tudos",
    "Hidden": "Escondido",
    "Zoom": "Zoom (PT-BR)",
  },
  "Screens": {
    "Splash": "Splash",
    "Onboarding": "Onboarding",
    "Terms": "Termos & Condições",
    "CreatePIN": "Criar um PIN",
    "EnterPIN": "Digitar o PIN",
    "Home": "Home",
    "Scan": "Scanear",
    "Credentials": "Credenciais",
    "CredentialDetails": "Detalhes de Credencial",
    "Notifications": "Notificações",
    "CredentialOffer": "Oferta de Credencial",
    "ProofRequest": "Requisição de Prova",
    "ProofRequestDetails": "Detalhes Da Solicitação De Comprovação",
    "ProofRequestAttributeDetails": "Atributos de Requisição de Prova",
    "ProofDetails": "Detalhes da prova",
    "Settings": "Configurações",
    "Language": "Idioma",
    "Tours": "App guides (PT-BR)",
    "Contacts": "Contatos",
    "Decline": "Recusar",
    "ContactDetails": "Detalhes do Contato",
    "Biometry": "Biometria",
    "Developer": "Developer options",
    "ChangePIN": "Alterar PIN",
    "ProofRequests": "Solicitações de prova",
    "SendProofRequest": "Envie um pedido de prova",
    "ChooseProofRequest": "Escolha um pedido de prova",
    "ProofRequestUsageHistory": "Histórico de uso",
    "ConnectionInvitation": "Convite de conexão",
    "CreateConnectionInvitation": "Criar um convite de conexão",
    "NameWallet": "Name your wallet (PT-BR)",
  },
  "Loading": {
    "TakingTooLong": "Isso esta demorando mais que o normal. Você pode voltar para a home ou continuar esperando.",
    "BackToHome": "Voltar para a home"
  },
  "NameWallet": {
    "NameYourWallet": "Name your wallet (PT-BR)",
    "ThisIsTheName": "This is the name people see when connecting with you. (PT-BR)",
    "CharCountTitle": "Character count exceeded (PT-BR)",
    "CharCountDescription": "You've exceeded the maximum character count of 50 characters. Please reduce your character count. (PT-BR)",
    "EmptyNameTitle": "Wallet name can't be empty (PT-BR)",
    "EmptyNameDescription": "This is the name people see when connecting with you.\n\nPlease enter a wallet name. (PT-BR)",
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Sem conexão com a internet",
    "NoInternetConnectionMessage": "Não é possivel acessar serviços utilizando a Bifold ou receber credenciais até você voltar a estar online.\n\nFavor checkar sua conexão com a internet.",
    "LedgerConnectivityIssueTitle": "Serviços de Carteira",
    "LedgerConnectivityIssueMessage": "Um firewall pode estar te impedindo de conectar-se a serviços relacionados a carteira.",
  },
  "Onboarding": {
    "SkipA11y": "Skip introduction to Aries Bifold (PT-BR)",
  },
  "Chat": {
    "OpenPresentation": "Open Presentation (PT-BR)",
    "ViewRequest": "View Request (PT-BR)",
    "ViewOffer": "View Offer (PT-BR)",
    "OpenItem": "Abrir",
    "UserYou": "Você",
    "CredentialProposalSent": "enviou uma proposta de credencial",
    "CredentialOfferReceived": "enviou uma oferta de credencial",
    "CredentialRequestSent": "enviou uma solicitação de credencial",
    "CredentialDeclined": "recusou uma oferta de credencial",
    "CredentialReceived": "recebeu uma credencial",
    "ProofRequestSent": "enviou uma solicitação de prova",
    "ProofPresentationReceived": "te enviou informações",
    "ProofRequestReceived": "recebeu uma solicitação de prova",
    "ProofRequestRejected": "rejeitou uma solicitação de prova",
    "ProofRequestRejectReceived": "rejeitou um pedido de prova",
    "ProofRequestSatisfied": "informações compartilhadas",
  },
  "Verifier": {
    "UseVerifierCapability": "Usar o recurso Verificador?",
    "UseDevVerifierTemplates": "Use development verifier templates? (PB)",
    "Toggle": "Alternar capacidade do verificador",
    "ToggleDevTemplates": "Toggle Verifier Development Templates (PB)",
    "ProcessingProof": "Um momento...",
    "ZeroKnowledgeProof": "Prova de conhecimento Zero",
    "Parameterizable": "Parametrizável",
    "RefreshQR": "Refresh QR Code (PB)",
    "GenerateNewQR": "Request another proof (PB)",
    "ShareLink": "Compartilhar link",
    "ScanQR": "Show this QR code to the other person (PB)",
    "ScanQRComment": "After the QR code is scanned, a proof request will be sent (PB).",
    "InformationReceived": "Information received. (PB)",
    "InformationReceivedDetails": "Review the information below. (PB)",
    "ProofVerificationFailed": "A verificação da prova falhou",
    "ViewDetails": "Ver detalhes",
    "HideDetails": "Detalhes ocultos",
    "UseProofRequest": "Envie d'une sollicitation de compromis",
    "SendThisProofRequest": "Envie esta solicitação de prova",
    "SendProofRequest": "Envie uma Solicitação de Comprovante",
    "EmptyList": "Sua carteira está vazia. Seus modelos de solicitação de prova serão adicionados aqui.",
    "ShowTemplateUsageHistory": "Mostrar histórico de uso",
    "RequestSent": "Pedido de apresentação enviado",
    "PresentationDeclined": "Pedido de apresentação recusado",
    "PresentationReceived": "Apresentação recebida",
    "PresentationFailed": "Falha na apresentação",
    "ProofRequestRejected": "Pedido de apresentação rejeitado",
    "PresentationFrom": "De",
    "PresentationState": "Estada",
    "ConnectionlessPresentation": "Sem conexão",
    'TutorialStep1Title': 'Mostrar este código QR para a outra pessoa',
    'TutorialStep1Description': 'Você se conectará com a outra pessoa. Eles receberão uma solicitação de prova.',
    "InvalidPredicateValueTitle": "Valor inválido para {{ predicate }}",
    "InvalidPredicateValueDetails": "Deve ser um número",
    "ConnectionLessLabel": "Anônimo"
  }
}

export default translation
