import { jest } from '@jest/globals'

export const useAgent = jest.fn()
export const useBasicMessages = jest.fn()
export const useBasicMessagesByConnectionId = jest.fn()
export const useConnections = jest.fn()
export const useConnectionById = jest.fn()
export const useCredentials = jest.fn()
export const useCredentialById = jest.fn()
export const useCredentialByState = jest.fn()
export const useCredentialNotInState = jest.fn()
export const useCredentialsByConnectionId = jest.fn()
export const useProofs = jest.fn()
export const useProofById = jest.fn()
export const useProofByState = jest.fn()
export const useProofNotInState = jest.fn()
export const useQuestionAnswer = jest.fn()
export const useQuestionAnswerByConnectionId = jest.fn()
export const useQuestionAnswerById = jest.fn()
export const useExchanges = jest.fn()
export const useExchangesByConnectionId = jest.fn()
export const useProofsByConnectionId = jest.fn()
export const useProofsFormatData = jest.fn()
export const useProofFormatDataById = jest.fn()
export const useCredentialFormatDataById = jest.fn()
export const useCredentialsFormatData = jest.fn()
