// prettier-ignore
const translation = {
    "Global": {
        "Enter": "Entrer",
        "Submit": "Soumettre",
        "NoneYet!": "Votre portefeuille est vide. Vos justificatifs acceptés seront ajoutés ici.",
        "Cancel": "Annuler",
        "Confirm": "Confirmer",
        "Accept": "Accepter",
        "Reject": "Rejeter",
        "NotNow": "Not now (FR)",
        "Share": "Partager",
        "Decline": "Refuser",
        "Back": "Retour",
        "Next": "Suivant",
        "Continue": "Continuer",
        "Info": "Information",
        "ThisDecisionCannotBeChanged": "Cette décision ne peut être modifiée.",
        "Failure": "Échec",
        "Success": "Succès",
        "SomethingWentWrong": "Un problème est survenu",
        "Done": "Terminé",
        "Skip": "Ignorer",
        "View": "Afficher",
        "Home": "Accueil",
        "ErrorCode": "Code d'erreur",
        "Okay": "Ok",
        "GoBack": "Retour",
        "GetStarted": "Commencer",
        "Dismiss": "Rejeter",
        "ShowDetails": "Afficher les détails",
        "TryAgain": "Réessayer",
        "Biometrics": "Biométrie",
        "On": "Activé",
        "Off": "Désactivé",
        "Close": "Close (FR)",
    },
    "Date": {
        "ShortFormat": "D MMM YYYY",
        "LongFormat": "D MMMM YYYY, HH:mm:ss",
        "MonthLong": {
            "January": "janvier",
            "February": "février",
            "March": "mars",
            "April": "avril",
            "May": "mai",
            "June": "juin",
            "July": "juillet",
            "August": "aout",
            "September": "septembre",
            "October": "octobre",
            "November": "novembre",
            "December": "décembre",
        },
        "MonthShort": {
            "January": "janv",
            "February": "févr",
            "March": "mars",
            "April": "avril",
            "May": "mai",
            "June": "juin",
            "July": "juil",
            "August": "août",
            "September": "sept",
            "October": "oct",
            "November": "nov",
            "December": "déc",
        }
    },
    "Language": {
        "English": "Anglais",
        "French": "Français",
        "Portuguese": "Portugais",
    },
    "Error": {
        "Unknown": "Erreur inconnue",
        "Problem": "Un problème est survenu",
        "ErrorCode": "Code d'erreur",
        "Title1024": "Impossible d'accepter l'offre de justificatif(s).",
        "Message1024": "Un problème est survenu lors de l'acceptation de l'offre de justificatif(s).",
        "Title1025": "Impossible de rejeter la demande de preuve.",
        "Message1025": "Il y a eu un problème lors du rejet de la demande de preuve.",
        "Title1026": "Impossible de mettre à jour les justificatifs récupérés.",
        "Message1026": "Un problème est survenu lors de la mise à jour des justificatifs récupérés.",
        "Title1027": "Impossible d'accepter la demande de preuve.",
        "Message1027": "Un problème est survenu lors de l'acceptation de la demande de preuve.",
        "Title1028": "Impossible de rejeter l'offre de justificatif(s).",
        "Message1028": "Un problème est survenu lors du rejet de l'offre de justificatif(s).",
        "Title1029": "Détails	Impossible de mettre à jour les justificatifs récupérés.",
        "Message1029": "Un problème est survenu lors de la mise à jour des justificatifs récupérés.",
        "Title1030": "Impossible d'accepter la connexion.",
        "Message1030": "Un problème est survenu lors de l'acceptation de la redirection de la connexion.",
        "Title1031": "Impossible d'accepter la connexion.",
        "Message1031": "Un problème est survenu lors de l'acceptation de la connexion.",
        "Title1032": "Impossible de retirer le justificatif.",
        "Message1032": "Un problème est survenu lors du retrait du justificatif.",
        "Title1033": "Impossible de récupérer le justificatif.",
        "Message1033": "Le justificatif est introuvable.",
        "Title1034": "Unable to fetch proof request. (FR)",
        "Message1034": "Proof request could not be found. (FR)",
        "Title1035": "Unable to fetch credential offer. (FR)",
        "Message1035": "Credential offer could not be found. (FR)",
        "Title1036": "Unable to fetch wallet credentials (FR)",
        "Message1036": "Wallet credentials could not be found (FR)",
        "Title1037": "Unable to remove contact. (FR)",
        "Message1037": "There was a problem while removing the contact. (FR)",
        "Title1038": "Impossible de générer une demande de justificatif",
        "Message1038": "Un problème est survenu lors de la génération d'une demande de preuve.",
    },
    "StatusMessages": {
        "InitAgent": "Initialisation de l'agent ..."
    },
    "Terms": {
        "TermsOfService": "Conditions d'utilisation",
        "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
        "IAgree": "J'accepte",
        "Attestation": "J'ai lu, je comprends et j'accepte les conditions."
    },
    "Tour": {
        "GuideTitle": "Welcome to Aries Bifold (FR)",
        "WouldYouLike": "Would you like some guidance on how to use Aries Bifold? (FR)",
        "UseAppGuides": "Use app guides (FR)",
        "DoNotUseAppGuides": "Don't use app guides (FR)",
        "AddAndShare": "Add and share credentials (FR)",
        "AddAndShareDescription": "To add and use credentials you scan a QR code displayed by the service provider. (FR)",
        "Notifications": "Notifications (FR)",
        "NotificationsDescription": "After you scan a QR code, the credential offer or proof request will appear here, as well as other notable events. (FR)",
        "YourCredentials": "Your credentials (FR)",
        "YourCredentialsDescription": "Your added digital credentials appear here. You can review credential details and add and delete credentials. (FR)",
        "Skip": "Skip (FR)",
        "Next": "Next (FR)",
        "Back": "Back (FR)",
        "Done": "Done (FR)",
      },
    "CameraDisclosure": {
        "AllowCameraUse": "Allow camera use (FR)",
        "CameraDisclosure": "La caméra est utilisée pour scanner les codes QR pour un traitement immédiat sur l'appareil. Aucune information sur les images n'est stockée, utilisée à des fins d'analyse ou partagée.",
        "ToContinueUsing": "To continue using the Aries Bifold scan feature, please allow camera permissions. (FR)",
        "Allow": "Allow (FR)",
        "OpenSettings": "Open settings (FR)",
    },
    "PINCreate": {
        "Message": {
            "CrossPatternValidation": "Un patron de croix a été détecté dans votre NIP. Veuillez saisir un NIP différent.",
            "OddOrEvenSequenceValidation": "Une séquence impaire ou paire a été détectée dans votre NIP. Veuillez saisir un NIP différent.",
            "NoRepetitionOfTheTwoSameNumbersValidation": "Une séquence de deux chiffres répétée a été détectée dans votre NIP. Veuillez saisir un NIP différent.",
            "NoRepetitionOfTheSameNumbersValidation": "Votre NIP possède des nombres consécutifs identiques. Veuillez saisir un NIP différent",
            "NoSeriesOfNumbersValidation": "Une suite a été détectée dans votre NIP. Veuillez saisir un NIP différent.",
            "PINOnlyContainDigitsValidation": "Votre NIP doit contenir que des chiffres. Veuillez saisir un NIP différent.",
            "PINTooShortValidation": "Votre NIP est trop court. Veuillez saisir un NIP différent.",
            "PINTooLongValidation": "Votre NIP est trop long. Veuillez saisir un NIP différent.",
        },
        "Helper": {
            "CrossPatternValidation": "Ne doit pas contenir un patron de croix.",
            "OddOrEvenSequenceValidation": "Ne doit pas contenir une suite paire ou impaire.",
            "NoRepetitionOfTheTwoSameNumbersValidation": "Ne doit pas contenir deux chiffres qui se répètent.",
            "NoRepetitionOfTheSameNumbersValidation": "Ne doit pas contenir de répétition.",
            "NoSeriesOfNumbersValidation": "Ne doit pas contenir de suite (123).",
            "PINOnlyContainDigitsValidation": "Doit contenir que des chiffres.",
            "PINTooShortValidation": "Le NIP est de la bonne longueur.",
            "PINTooLongValidation": "Le NIP est de la bonne longueur.",
        },
        "UserAuthenticationPIN": "NIP d'authentification de l'utilisateur",
        "PINTooShort": "NIP trop court",
        "InvalidPIN": "NIP invalide",
        "PINsDoNotMatch": "Les NIP ne correspondent pas",
        "PleaseUseOnlyNumbersInYourPIN": "Veuillez utiliser uniquement des chiffres dans votre NIP",
        "YourPINMustBe6DigitsInLength": "Votre NIP doit être composé de six chiffres",
        "EnteredPINsDoNotMatch": "Les NIP saisis ne correspondent pas. Veuillez réessayer.",
        "YouNeedToCreateA6DigitPIN": "Vous devez créer un NIP à 6 chiffres",
        "PleaseReenterYourPIN": "Veuillez saisir à nouveau votre NIP",
        "EnterPINTitle": "Entrez un NIP à 6 chiffres",
        "EnterPIN": "Saisir un NIP à 6 chiffres",
        "ReenterPIN": "Saisir le NIP à nouveau",
        "CreatePIN": "Créer un NIP",
        "ReenterPINTitle": "Entrez à nouveau le code NIP",
        "RememberPIN": "Mémorisez votre NIP.",
        "PINDisclaimer": "Si vous l'oubliez, vous devrez configurer à nouveau votre portefeuille et ajouter à nouveau vos cartes.",
        "Show": "Afficher NIP",
        "Hide": "Masquer NIP",
        "ChangePIN": "Changer votre NIP",
        "Continue": "Continuer",
        "EnterYourCurrentPIN": "Entrez votre NIP actuel"
    },
    "PINEnter": {
        "EnterPIN": "Veuillez saisir votre NIP",
        "Unlock": "Déverrouiller",
        "Or": "Ou",
        "BiometricsUnlock": "Déverrouiller avec la biométrie",
        "IncorrectPIN": "NIP erroné",
        "RepeatPIN": "Essayez votre NIP à nouveau",
        "EnableBiometrics": "Vous devez activer la biométrie pour pouvoir charger le portefeuille.",
        "BiometricsNotProvided": "Biométrie non fournie, vous pouvez utiliser le NIP pour vous connecter au portefeuille.",
        "BiometricsError": "Biometrics were not successful.",
        "BiometricsErrorEnterPIN": "Please enter your wallet PIN.",
        "LoggedOut": "Vous avez été déconnecté du portefeuille.",
        "LoggedOutDescription": "Pour protéger vos informations, vous êtes déconnecté de votre portefeuille si vous ne l'avez pas utilisé pendant 5 minutes.",
        "BiometricsChanged": "Le déverrouillage avec la biométrie a été désactivé, car les données biométriques de votre appareil ont changé.",
        "BiometricsChangedEnterPIN": "Veuillez saisir le code NIP de votre portefeuille.",
        "AttemptLockoutWarning": "Note: pour votre sécurité, la saisie d'un autre NIP incorrect verrouillera temporairement le portefeuille."
    },
    "AttemptLockout": {
        "Title": "Votre portefeuille est temporairement verrouillé",
        "Description": "Vous avez eu trop de tentatives infructueuses.",
        "TryAgain": "Vous pouvez réessayer dans: ",
        "Hours": "heures",
        "Minutes": "minutes",
        "Seconds": "secondes",
    },
    "Biometry": {
        "Toggle": "Basculer la biométrie",
        "EnabledText1": "Déverrouiller votre portefeuille avec la biométrie de votre appareil au lieu d’utiliser le NIP du portefeuille.",
        "EnabledText2": "Toute personne qui a des données biométriques enregistrées sur cet appareil pourra déverrouiller votre portefeuille et avoir accès à vos attestations.",
        "NotEnabledText1": "La biométrie n'est pas actuellement configurée sur cet appareil et ne peut donc pas être activée.",
        "NotEnabledText2": "Si vous souhaitez activer cette fonctionnalité, activez la biométrie dans les paramètres de l'appareil, puis revenez à cet écran.",
        "Warning": "\n\nAssurez-vous que vous seul avez accès à votre portefeuille.",
        "UseToUnlock": "Utiliser la biométrie pour déverrouiller le portefeuille ?",
        "UnlockPromptTitle": "Déverrouillage du portefeuille",
        "UnlockPromptDescription": "Utilisez la biométrie pour déverrouiller votre portefeuille"
    },
    "Contacts": {
        "EmptyList": "Votre portefeuille est vide. Vos contacts connectés seront ajoutés ici.",
    },
    "ContactDetails": {
        "Created": "Créé",
        "ConnectionState": "État de la connexion",
        "AContact": "Un contact",
        "DateOfConnection": "Date of connection: {{ date }} (FR)",
        "RemoveTitle": "Remove this contact (FR)",
        "RemoveCaption": "To add credentials, the issuing organization needs to be a contact. (FR)",
        "UnableToRemoveTitle": "Unable to remove contact (FR)",
        "UnableToRemoveCaption": "Unable to remove because there are credentials issued by this contact in your wallet. Remove the credentials first then remove this contact. (FR)",
        "GoToCredentials": "Go to Credentials (FR)",
        "ContactRemoved": "Contact removed (FR)"
    },
    "WhatAreContacts": {
        "Title": "What are Contacts? (FR)",
        "Preamble": "Adding organizations as a Contact will allow you to: (FR)",
        "ListItemCredentialUpdates": "Get updates to credentials issued by this organization (FR)",
        "ListItemNewCredentials": "Get offered new credentials (FR)",
        "ListItemProofRequest": "Fast-track proof requests (FR)",
        "RemoveContacts": "You can always remove Contacts at any time from your (FR)",
        "ContactsLink": "Contacts list (FR)",
        "ContactSharing": "Use of your credentials is never shared with your Contacts. (FR)"
    },
    "Credentials": {
        "CredentialsNotFound": "Justificatifs non trouvés",
        "CredentialDetails": "Détails des justificatifs",
        "EmptyList": "Votre portefeuille est vide. Vos justificatifs acceptés seront ajoutés ici.",
    },
    "CredentialDetails": {
        "Id": "Identifiant :",
        "CreatedAt": "Créé à :",
        "Version": "Version",
        "Issued": "Délivré",
        "PrivacyPolicy": "Politique de confidentialité",
        "TermsAndConditions": "Conditions d'utilisation",
        "RemoveFromWallet": "Retirer du portefeuille",
        "Revoked": "Révoqué",
        "CredentialRevokedMessageTitle": "Ce justificatif est révoqué",
        "CredentialRevokedMessageBody": "Ce justificatif peut ne plus fonctionner pour certaines demandes de preuve. Vous devrez mettre à jour le justificatif avec l'émetteur.",
        "NewRevoked": "Credential revoked (FR)",
        "RemoveTitle": "Retirer le justificatif du portefeuille",
        "RemoveCaption": "Vous allez perdre la capacité d'utiliser ce portefeuille afin de prouver l'information se trouvant sur ce justificatif.",
        "CredentialNotFound": "Justificatif non trouvé",
        "YouWillNotLose": "Vous n'allez PAS perdre",
        "YouWillNotLoseListItem1": "Votre justificatif à l'intérieur du système de l'émetteur.",
        "YouWillNotLoseListItem2": "L'organisme émetteur en tant que contact.",
        "HowToGetThisCredentialBack": "Comment récupérer cet identifiant",
        "HowToGetThisCredentialBackListItem1": "Vous devrez vous rendre auprès de l'organisme qui vous a délivré ce justificatif et le redemander.",
        "CredentialRemoved": "Justificatif retiré",
        "IssuedBy": "Émis par:"
    },
    "Home": {
        "Welcome": "Bienvenue",
        "Notification": "Notification",
        "Notifications": "Notifications",
        "OneNotification": "1 Notification",
        "CountNotifications": "{{ count }} Notification",
        "NoNewUpdates": "Vous n'avez pas de nouvelles notifications.",
        "NoCredentials": "Vous n'avez pas de justificatifs dans votre portefeuille.",
        "SeeAll": "Voir tout",
        "YouHave": "Vous avez",
        "Credential": "justificatif",
        "Credentials": "justificatifs",
        "InYourWallet": "dans votre portefeuille"
    },
    "Scan": {
        "SuccessfullyAcceptedConnection": "Connexion acceptée avec succès",
        "AcceptingConnection": "Acceptation de la connexion",
        "ConnectionRecordIdNotFound": "Identifiant de l'enregistrement de connexion non trouvé",
        "ConnectionAccepted": "Connexion acceptée",
        "ConnectionNotFound": "Connexion non trouvée",
        "InvalidQrCode": "Code QR non valide. Veuillez réessayer.",
        "UnableToHandleRedirection": "Impossible de traiter la redirection",
        "Close": "Fermer",
        "Torch": "Flash"
    },
    "Connection": {
        "JustAMoment": "Veuillez patienter pendant que nous établissons une connexion sécurisée...",
        "TakingTooLong": "Cela prend plus de temps que d'habitude. Vous pouvez retourner à l'accueil ou continuer à attendre.",
        "ConnectionInvitation": "Invitation de connexion",
        "ScanQR": "Scannez ce QR Code",
        "ScanQRComment": "avec votre portefeuille numérique pour établir une connexion.",
        "MakingConnection": "Faire le lien...",
        "ConnectionCompleted": "Connexion terminée !",
        "Toggle": "Basculer la capacité d'invitation à la connexion",
        "UseConnectionInviterCapability": "Utiliser la fonction d'invitation à la connexion ?",
        "OpenContact": "Contact ouvert",
    },
    "ConnectionAlert": {
        "AddedContacts": "Ajouté aux contacts",
        "WhatAreContacts": "Que sont les contacts ?",
        "NotificationBodyUpper": "Vous pouvez trouver ",
        "NotificationBodyLower": " dans vos contacts. Gérez vos contacts dans les paramètres",
        "PopupIntro": "L'ajout d'organisations en tant que contact vous permettra de: ",
        "PopupPoint1": "Obtenir des mises à jour des informations d'identification émises par cette organisation",
        "PopupPoint2": "Obtenir de nouvelles informations d'identification",
        "PopupPoint3": "Demandes de preuves accélérées",
        "SettingsLink": "Réglages",
        "SettingsInstruction": "Vous pouvez à tout moment supprimer des contacts dans ",
        "PrivacyMessage": "L'utilisation de vos informations d'identification n'est jamais partagée avec vos contacts.",
        "PopupExit": "J'ai compris"
    },
    "CredentialOffer": {
        "CredentialOffer": "Offre de justificatif",
        "ThisIsTakingLongerThanExpected": "Cela prend plus de temps que prévu. Revenez plus tard pour votre nouveau justificatif.",
        "RejectThisCredential?": "Rejeter ce justificatif?",
        "AcceptingCredential": "Acceptation du justificatif",
        "SuccessfullyAcceptedCredential": "Justificatif accepté avec succès",
        "RejectingCredential": "Rejet du justificatif",
        "SuccessfullyRejectedCredential": "Justificatif rejeté avec succès",
        "CredentialNotFound": "Justificatif non trouvé",
        "CredentialAccepted": "Justificatif accepté",
        "CredentialRejected": "Justificatif rejeté",
        "CredentialAddedToYourWallet": "Justificatif ajouté à votre portefeuille",
        "CredentialDeclined": "Justificatif refusé",
        "CredentialOnTheWay": "Votre justificatif est en cours de transmission",
        "NewCredentialOffer": "Nouvelle offre de justificatif",
        "IsOfferingYouACredential": "vous offre un justificatif",
        "ConfirmDeclineCredential": "Oui, refuser ce justificatif",
        "AbortDeclineCredential": "Non, revenir en arrière",
        "ConfirmDecline": "Oui, décliner le justificatif",
        "ConfirmDeclinedTitle": "Êtes-vous sûr de vouloir refuser ce justificatif?",
        "ConfirmDeclinedMessage": "Afin de recevoir à nouveau ce justificatif, vous devrez présenter une nouvelle demande auprès de l'émetteur.",
        "AbortDecline": "Non, revenir en arrière",
        "DeclineTitle": "Refuser le justificatif",
        "Declined": "Diminué",
    },
    "ProofRequest": {
        "ProofRequest": "Demande de preuve",
        "RequestProcessing": "Juste un instant...",
        "OfferDelay": "Retard de l'offre",
        "RejectThisProof?": "Rejeter cette preuve?",
        "AcceptingProof": "Acceptation de la preuve",
        "SuccessfullyAcceptedProof": "Preuve acceptée avec succès",
        "RejectingProof": "Rejet de la preuve",
        "ProofAccepted": "Preuve acceptée",
        "ProofRejected": "Preuve rejetée",
        "RequestedCredentialsCouldNotBeFound": "Les justificatifs demandés n'ont pas été trouvés",
        "NewProofRequest": "Nouvelle demande de preuve",
        "NotAvailableInYourWallet": "Non disponible dans votre portefeuille",
        "IsRequesting": "demande",
        "IsRequestingSomethingYouDontHaveAvailable": "demande quelque chose que vous n'avez pas à votre disposition",
        "IsRequestingYouToShare": "is requesting the following information from",
        "Credential": "credential.",
        "Credentials": "credentials.",
        "WhichYouCanProvideFrom": "que vous pouvez fournir à partir de",
        "Details": "Détails",
        "SendingTheInformationSecurely": "Envoi sécurisé de l'information",
        "InformationSentSuccessfully": "Informations envoyées avec succès",
        "ProofRequestDeclined": "Demande de preuve refusée",
        "DeclineTitle": "Decline Credential",
        "Declined": "Diminué",
        "ShareFollowingInformation_one": "partage les informations suivantes à partir des informations d'identification {{count}}.",
        "ShareFollowingInformation_other": "partage les informations suivantes à partir des informations d'identification {{count}}."
    },
    "Settings": {
        "Version": "Version",
        "VersionString": "0.0.0-0",
        "AppSettings": "Réglage de l'application",
        "AboutApp": "À propos de l'application",
        "Language": "Langue",
        "AppGuides": "App guides (FR)",
        "Build": "Build",
        "WhatAreContacts": "Qu’est-ce qu’un contact?",
        "Developer": "Developer options"
    },
    "TabStack": {
        "Home": "Accueil",
        "Scan": "Numériser",
        "Credentials": "Justificatifs"
    },
    "RootStack": {
        "Contacts": "Contacts",
        "Settings": "Paramètres"
    },
    "QRScanner": {
        "PermissionToUseCamera": "Permission d'utiliser l'appareil photo",
        "WeNeedYourPermissionToUseYourCamera": "Nous avons besoin de votre permission pour utiliser votre appareil photo",
        "Ok": "Ok"
    },
    "QRRender": {
        "GenerationError": "Impossible de générer le code QR",
    },
    "Record": {
        "Hide": "Masquer",
        "Show": "Afficher",
        "HideAll": "Masquer tout",
        "Hidden": "Masqué",
        "InvalidDate": "Date invalide: ",
    },
    "Screens": {
        "Splash": "Page de garde",
        "Onboarding": "Inscription",
        "Terms": "Conditions d'utilisation",
        "CreatePIN": "Créer un NIP à 6 chiffres",
        "EnterPIN": "Saisir le NIP",
        "Home": "Accueil",
        "Scan": "Numériser",
        "Credentials": "Justificatifs",
        "CredentialDetails": "Détails des justificatifs",
        "Notifications": "Notifications",
        "CredentialOffer": "Offre de justificatif",
        "ProofRequest": "Demande de preuve",
        "ProofRequestAttributeDetails": "Détails des attributs de la demande de preuve",
        "ProofDetails": "Détails de la preuve",
        "Settings": "Paramètres",
        "Language": "Langue",
        "Tours": "App guides (FR)",
        "Contacts": "Contacts",
        "Decline": "Refuser",
        "ContactDetails": "Informations du contact",
        "Biometry": "Biométrie",
        "Developer": "Developer options",
        "ChangePIN": "Changer NIP",
        "CommonDecline": "Refuser",
        "ProofRequests": "Demandes de preuve",
        "ProofRequestDetails": "Détails de la Demande d'Épreuve",
        "SendProofRequest": "Envoyer une demande de justificatif",
        "ChooseProofRequest": "Choisissez une demande de justificatif",
        "ProofRequestUsageHistory": "Historique d'utilisation",
        "ConnectionInvitation": "Invitation de connexion",
        "CreateConnectionInvitation": "Créer une invitation de connexion",
    },
    "Loading": {
        "TakingTooLong": "Cela prend plus de temps que d'habitude. Vous pouvez retourner à l'accueil ou continuer à attendre.",
        "BackToHome": "Retour à l'accueil"
    },
    "NetInfo": {
        "NoInternetConnectionTitle": "Aucune connexion Internet",
        "NoInternetConnectionMessage": "Vous ne pouvez pas accéder aux services à l'aide de Bifold ou recevoir des informations d'identification tant que vous n'êtes pas de nouveau en ligne.\n\nS'il vous plait, vérifiez votre connexion internet.",
        "LedgerConnectivityIssueTitle": "Wallet Services (FR)",
        "LedgerConnectivityIssueMessage": "A firewall may be preventing you from connecting to wallet related services. (FR)",
    },
    "Chat": {
        "OpenItem": "Ouvrir",
        "UserYou": "Vous avez",
        "CredentialProposalSent": "envoyé une proposition d'accréditation",
        "CredentialOfferReceived": "a envoyé une offre d'accréditation",
        "CredentialRequestSent": "envoyé une demande d'informations d'identification",
        "CredentialDeclined": "refusé une offre d'accréditation",
        "CredentialReceived": "reçu une attestation",
        "ProofRequestSent": "envoyé une demande de justificatif",
        "ProofPresentationReceived": "vous a envoyé des informations",
        "ProofRequestReceived": "reçu une demande de justificatif",
        "ProofRequestRejected": "rejeté une demande de justificatif",
        "ProofRequestRejectReceived": "a rejeté une demande de justificatif",
        "ProofRequestSatisfied": "informations partagées",
    },
    "Verifier": {
        "UseVerifierCapability": "Utiliser la fonctionnalité Verifier?",
        "Toggle": "Basculer la capacité de vérification",
        "ProcessingProof": "Juste un moment...",
        "ZeroKnowledgeProof": "Preuve zéro connaissance",
        "Parameterizable": "Paramétrable",
        "GenerateNewQR": "Générer un nouveau code QR",
        "ShareLink": "Lien de partage",
        "ScanQR": "Scannez ce QR Code",
        "ScanQRComment": "avec votre portefeuille numérique pour recevoir une demande de justificatif.",
        "InformationReceived": "Information reçue",
        "InformationReceivedDetails": "partagé les informations suivantes.",
        "ProofVerificationFailed": "La vérification de la preuve a échoué",
        "ViewDetails": "Voir les détails",
        "HideDetails": "Cacher les détails",
        "UseProofRequest": "Utilisez cette demande de preuve",
        "SendThisProofRequest": "Envoyer cette demande de justificatif",
        "SendProofRequest": "Envoyer une demande de preuve",
        "EmptyList": "Sua carteira está vazia. Seus modelos de solicitação de prova serão adicionados aqui.",
        "ShowTemplateUsageHistory": "Afficher l'historique d'utilisation",
        "RequestSent": "Demande de présentation envoyée",
        "PresentationDeclined": "Demande de présentation refusée",
        "PresentationReceived": "Présentation reçue",
        "PresentationFailed": "La présentation a échoué",
        "ProofRequestRejected": "Demande de présentation rejetée",
        "PresentationFrom": "Depuis",
        "PresentationState": "État",
        "ConnectionlessPresentation": "Sans connexion",
        'TutorialStep1Title': 'Montrez ce code QR à l\'autre personne',
        'TutorialStep1Description': 'Vous vous connecterez avec l\'autre personne. Ils recevront une demande de justificatif.',
        "InvalidPredicateValueTitle": "Valeur invalide pour {{ predicate }}",
        "InvalidPredicateValueDetails": "Doit être un nombre",
        "ConnectionLessLabel": "Anonyme"
    }
}
export default translation
