source 'https://rubygems.org'
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"
gem 'cocoapods', '~> 1.14.3', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '~> 7.0.8', '!= 7.1.0'

gem 'concurrent-ruby', '< 1.3.4'
 
# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'