// prettier-ignore
const translation = {
    "Global": {
        "Submit": "Soumettre",
        "NoneYet!": "Votre portefeuille est vide. Vos justificatifs acceptés seront ajoutés ici.",
        "Cancel": "Annuler",
        "Confirm": "Confirmer",
        "Accept": "Accepter",
        "Reject": "Rejeter",
        "Share": "Partager",
        "Decline": "Refuser",
        "Back": "Retour",
        "Next": "Suivant",
        "Continue": "Continuer",
        "Info": "Information",
        "ThisDecisionCannotBeChanged": "Cette décision ne peut être modifiée.",
        "Failure": "Échec",
        "Success": "Succès",
        "SomethingWentWrong": "Un problème est survenu",
        "Done": "Terminé",
        "Skip": "Ignorer",
        "View": "Afficher",
        "Home": "Accueil",
        "ErrorCode": "Code d'erreur",
        "Okay": "Ok",
        "GoBack": "Retour",
        "GetStarted": "Commencer",
        "Dismiss": "Rejeter",
        "ShowDetails": "Afficher les détails",
    },
    "Language": {
        "English": "Anglais",
        "French": "Français"
    },
    "Error": {
        "Unknown": "Erreur inconnue",
        "Problem": "Un problème est survenu",
        "ErrorCode": "Code d'erreur",
        "Title1025": "Impossible de rejeter la demande de preuve.",
        "Message1025": "Il y a eu un problème lors du rejet de la demande de preuve.",
        "Title1024": "Impossible d'accepter l'offre de justificatif(s).",
        "Message1024": "Un problème est survenu lors de l'acceptation de l'offre de justificatif(s).",
        "Title1026": "Impossible de mettre à jour les justificatifs récupérés.",
        "Message1026": "Un problème est survenu lors de la mise à jour des justificatifs récupérés.",
        "Title1027": "Impossible d'accepter la demande de preuve.",
        "Message1027": "Un problème est survenu lors de l'acceptation de la demande de preuve.",
        "Title1029": "Détails	Impossible de mettre à jour les justificatifs récupérés.",
        "Message1029": "Un problème est survenu lors de la mise à jour des justificatifs récupérés.",
        "Title1028": "Impossible de rejeter l'offre de justificatif(s).",
        "Message1028": "Un problème est survenu lors du rejet de l'offre de justificatif(s).",
        "Title1030": "Impossible d'accepter la connexion.",
        "Message1030": "Un problème est survenu lors de l'acceptation de la redirection de la connexion.",
        "Title1031": "Impossible d'accepter la connexion.",
        "Message1031": "Un problème est survenu lors de l'acceptation de la connexion.",
    },
    "StatusMessages": {
        "InitAgent": "Initialisation de l'agent ..."
    },
    "Terms": {
        "TermsOfService": "Conditions d'utilisation",
        "TermsOfServiceText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel consectetur diam. Nunc sit amet elit est. Praesent libero elit, consectetur dapibus diam non, facilisis euismod velit. Etiam a ligula eget leo elementum tincidunt. Fusce et lorem turpis. Nunc tempus nisl consectetur eros vehicula venenatis. Suspendisse potenti. Aenean vitae aliquet augue. Maecenas lacinia nunc vitae blandit hendrerit. Sed congue risus quis magna convallis sollicitudin. Integer in ante vel orci ornare porta quis id libero. Proin mollis urna nec lectus fringilla, sit amet aliquam urna fringilla. Praesent pellentesque non augue et gravida. Donec congue urna ac massa consequat, lacinia condimentum dolor blandit. Nam ultrices tellus at risus dignissim, quis cursus mauris pellentesque. Donec at scelerisque ipsum. Praesent eu massa at tellus cursus ornare. Fusce vel faucibus dolor. Etiam blandit velit sed velit tempus feugiat. Donec condimentum pretium suscipit. Sed suscipit, leo molestie tempus maximus, turpis enim hendrerit nibh, semper sagittis turpis velit sed nisl. Aliquam eu ultrices velit. Aenean tristique mauris justo, eu commodo quam semper non. Curabitur ultricies auctor mi eu tempus. Sed bibendum eros sed neque semper fermentum. Nullam porta tortor ut ante congue molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sit amet aliquam nunc, malesuada auctor quam. Pellentesque vel lobortis risus, volutpat suscipit velit. Aenean ut erat sed metus interdum mattis. Nam consectetur ante eu felis rhoncus, et volutpat dolor tincidunt. Vivamus sit amet feugiat mi. Proin in dui ac metus vehicula fringilla eget id mauris. Maecenas et elit venenatis dolor pulvinar pulvinar in et leo. Aliquam scelerisque viverra sapien at bibendum. Curabitur et libero nec enim convallis porttitor sed a libero. In hac habitasse platea dictumst. Integer dignissim velit eu pharetra ultricies. Vestibulum at velit hendrerit, pretium purus eget, lobortis tellus. Maecenas non erat ut lacus scelerisque luctus et et tellus.",
        "IAgree": "J'accepte",
        "Attestation": "J'ai lu, je comprends et j'accepte les conditions."
    },
    "PinCreate": {
        "UserAuthenticationPIN": "NIP d'authentification de l'utilisateur",
        "PINTooShort": "NIP trop court",
        "InvalidPIN": "NIP invalide",
        "PINsDoNotMatch": "Les NIP ne correspondent pas",
        "PleaseUseOnlyNumbersInYourPIN": "Veuillez utiliser uniquement des chiffres dans votre NIP",
        "YourPINMustBe6DigitsInLength": "Votre NIP doit être composé de six chiffres",
        "EnteredPINsDoNotMatch": "Les NIP saisis ne correspondent pas. Veuillez réessayer.",
        "YouNeedToCreateA6DigitPIN": "Vous devez créer un NIP à 6 chiffres",
        "PleaseReenterYourPIN": "Veuillez saisir à nouveau votre NIP",
        "EnterPIN": "Saisir un NIP à 6 chiffres",
        "ReenterPIN": "Saisir le NIP à nouveau",
        "CreatePIN": "Créer un NIP",
        "RememberPIN": "Mémorisez votre NIP.",
        "PINDisclaimer": "Si vous l'oubliez, vous devrez configurer à nouveau votre portefeuille et ajouter à nouveau vos cartes.",
      },
    "PinEnter": {
        "IncorrectPIN": "NIP erroné",
        "EnterPIN": "Veuillez saisir votre NIP",
    },
    "ContactDetails": {
        "Created": "Créé",
        "ConnectionState": "État de la connexion",
        "AContact": "Un contact"
    },
    "Credentials": {
        "CredentialsNotFound": "Justificatifs non trouvés",
        "CredentialDetails": "Détails des justificatifs"
    },
    "CredentialDetails": {
        "Id": "Identifiant :",
        "CreatedAt": "Créé à :",
        "Version": "Version",
        "Issued": "Délivré",
        "PrivacyPolicy": "Politique de confidentialité",
        "TermsAndConditions": "Conditions d'utilisation",
        "RemoveFromWallet": "Retirer du portefeuille",
        "Revoked": "Révoqué",
        "CredentialRevokedMessageTitle": "Ce justificatif est révoqué",
        "CredentialRevokedMessageBody": "Ce justificatif peut ne plus fonctionner pour certaines demandes de preuve. Vous devrez mettre à jour le justificatif avec l'émetteur."
    },
    "Home": {
        "Welcome": "Bienvenue",
        "Notifications": "Notifications",
        "NoNewUpdates": "Vous n'avez pas de nouvelles notifications.",
        "NoCredentials": "Vous n'avez pas de justificatifs dans votre portefeuille.",
        "SeeAll": "Voir tout",
        "YouHave": "Vous avez",
        "Credential": "justificatif",
        "Credentials": "justificatifs",
        "InYourWallet": "dans votre portefeuille"
    },
    "Scan": {
        "SuccessfullyAcceptedConnection": "Connexion acceptée avec succès",
        "AcceptingConnection": "Acceptation de la connexion",
        "ConnectionRecordIdNotFound": "Identifiant de l'enregistrement de connexion non trouvé",
        "ConnectionAccepted": "Connexion acceptée",
        "ConnectionNotFound": "Connexion non trouvée",
        "InvalidQrCode": "Code QR non valide. Veuillez réessayer.",
        "UnableToHandleRedirection": "Impossible de traiter la redirection",
        "Close": "Fermer",
        "Torch": "Flash"
    },
    "Connection": {
        "JustAMoment": "Veuillez patienter pendant que nous établissons une connexion sécurisée...",
        "TakingTooLong": "Cela prend plus de temps que d'habitude. Vous pouvez retourner à l'accueil ou continuer à attendre."
    },
    "CredentialOffer": {
        "CredentialOffer": "Offre de justificatif",
        "ThisIsTakingLongerThanExpected": "Cela prend plus de temps que prévu. Revenez plus tard pour votre nouveau justificatif.",
        "RejectThisCredential?": "Rejeter ce justificatif?",
        "AcceptingCredential": "Acceptation du justificatif",
        "SuccessfullyAcceptedCredential": "Justificatif accepté avec succès",
        "RejectingCredential": "Rejet du justificatif",
        "SuccessfullyRejectedCredential": "Justificatif rejeté avec succès",
        "CredentialNotFound": "Justificatif non trouvé",
        "CredentialAccepted": "Justificatif accepté",
        "CredentialRejected": "Justificatif rejeté",
        "CredentialAddedToYourWallet": "Justificatif ajouté à votre portefeuille",
        "CredentialDeclined": "Justificatif refusé",
        "CredentialOnTheWay": "Votre justificatif est en cours de transmission",
        "NewCredentialOffer": "Nouvelle offre de justificatif",
        "IsOfferingYouACredential": "vous offre un justificatif",
        "ConfirmDeclineCredential": "Oui, refuser ce justificatif",
        "AbortDeclineCredential": "Non, revenir en arrière",
        "DeclineTitle": "Decline Credential",
    },
    "ProofRequest": {
        "ProofRequest": "Demande de preuve",
        "OfferDelay": "Retard de l'offre",
        "RejectThisProof?": "Rejeter cette preuve?",
        "AcceptingProof": "Acceptation de la preuve",
        "SuccessfullyAcceptedProof": "Preuve acceptée avec succès",
        "ProofNotFound": "Preuve non trouvée",
        "RejectingProof": "Rejet de la preuve",
        "ProofAccepted": "Preuve acceptée",
        "ProofRejected": "Preuve rejetée",
        "RequestedCredentialsCouldNotBeFound": "Les justificatifs demandés n'ont pas été trouvés",
        "NewProofRequest": "Nouvelle demande de preuve",
        "NotAvailableInYourWallet": "Non disponible dans votre portefeuille",
        "IsRequesting": "demande",
        "IsRequestingSomethingYouDontHaveAvailable": "demande quelque chose que vous n'avez pas à votre disposition",
        "IsRequestingYouToShare": "vous demande de partager",
        "WhichYouCanProvideFrom": "que vous pouvez fournir à partir de",
        "Details": "Détails",
        "SendingTheInformationSecurely": "Envoi sécurisé de l'information",
        "InformationSentSuccessfully": "Informations envoyées avec succès",
        "ProofRequestDeclined": "Demande de preuve refusée",
        "DeclineTitle": "Decline Credential",
    },
    "Settings": {
        "Version": "Version",
        "VersionString": "0.0.0-0",
        "AppPreferences": "Préférences de l'application",
        "AboutApp": "À propos de l'application",
        "Language": "Langue"
    },
    "TabStack": {
        "Home": "Accueil",
        "Scan": "Numériser",
        "Credentials": "Justificatifs"
    },
    "RootStack": {
        "Contacts": "Contacts",
        "Settings": "Paramètres"
    },
    "QRScanner": {
        "PermissionToUseCamera": "Permission d'utiliser l'appareil photo",
        "WeNeedYourPermissionToUseYourCamera": "Nous avons besoin de votre permission pour utiliser votre appareil photo",
        "Ok": "Ok"
    },
    "Record": {
        "Hide": "Masquer",
        "Show": "Afficher",
        "HideAll": "Masquer tout",
        "Hidden": "Masqué"
    },
    "Screens": {
        "Splash": "Page de garde",
        "Onboarding": "Inscription",
        "Terms": "Conditions d'utilisation",
        "CreatePin": "Créer un NIP à 6 chiffres",
        "EnterPin": "Saisir le NIP",
        "Home": "Accueil",
        "Scan": "Numériser",
        "Credentials": "Justificatifs",
        "CredentialDetails": "Détails des justificatifs",
        "Notifications": "Notifications",
        "CredentialOffer": "Offre de justificatif",
        "ProofRequest": "Demande de preuve",
        "ProofRequestAttributeDetails": "Détails des attributs de la demande de preuve",
        "Settings": "Paramètres",
        "Language": "Langue",
        "Contacts": "Contacts",
        "ContactDetails": "Coordonnées"
    },
    "Loading": {
        "TakingTooLong": "Cela prend plus de temps que d'habitude. Vous pouvez retourner à l'accueil ou continuer à attendre.",
        "BackToHome": "Retour à l'accueil"
    }
}
export default translation
